import StochLean

/-! Kernel trust checks for milestone declarations. -/

#print axioms PMF.ext_pgf
#print axioms PMF.tendsto_pgf_of_tendsto_mass
#print axioms PMF.tendsto_mass_of_tendsto_pgf
#print axioms PMF.tendsto_pgf_iff_tendsto_mass
#print axioms PMF.pgf_randomSum
#print axioms ProbabilityTheory.GaltonWatson.pgf_extinctionProbability
#print axioms ProbabilityTheory.GaltonWatson.extinctionProbability_le_fixed
#print axioms ProbabilityTheory.IsPoissonProcess.hasStationaryIncrements
#print axioms ProbabilityTheory.PoissonProcess.DivergentArrivalSequence.count_eventTime
#print axioms ProbabilityTheory.tendsto_empiricalCDFSequence_ae
#print axioms ProbabilityTheory.tendsto_empiricalCDFSequence_rat_ae
#print axioms MeasureTheory.tendstoLocallyInMeasure_of_tendsto_ae
#print axioms MeasureTheory.TendstoLocallyInMeasure.exists_seq_tendsto_ae_restrict
#print axioms MeasureTheory.TendstoLocallyInMeasure.exists_seq_tendsto_ae
#print axioms MeasureTheory.exists_seq_tendstoLocallyInMeasure_atTop_iff
#print axioms MeasureTheory.TendstoLocallyInMeasure.tendsto_eLpNorm_restrict
