import StochLean

/-! Kernel trust checks for milestone declarations. -/

#print axioms PMF.ext_pgf
#print axioms PMF.tendsto_pgf_of_tendsto_mass
#print axioms PMF.tendsto_mass_of_tendsto_pgf
#print axioms PMF.tendsto_pgf_iff_tendsto_mass
#print axioms PMF.pgf_randomSum
#print axioms ProbabilityTheory.poissonBinomial_tendsto_poissonNat
#print axioms ProbabilityTheory.poissonBinomial_tendsto_poissonNat_of_max
#print axioms ProbabilityTheory.GaltonWatson.pgf_extinctionProbability
#print axioms ProbabilityTheory.GaltonWatson.extinctionProbability_le_fixed
#print axioms ProbabilityTheory.IsPoissonProcess.hasStationaryIncrements
#print axioms ProbabilityTheory.IsPoissonProcess.satisfiesPoissonIntervalAxioms
#print axioms ProbabilityTheory.SatisfiesPoissonIntervalAxioms.intervalMean_linear
#print axioms ProbabilityTheory.SatisfiesPoissonIntervalAxioms.tendsto_rareMultipleJump_ratio
#print axioms ProbabilityTheory.PoissonProcess.DivergentArrivalSequence.count_eventTime
#print axioms ProbabilityTheory.tendsto_empiricalCDFSequence_ae
#print axioms ProbabilityTheory.tendsto_empiricalCDFSequence_rat_ae
#print axioms ProbabilityTheory.tendsto_empiricalCDFSequence_all_ae
#print axioms ProbabilityTheory.tendsto_empiricalCDFSequenceLt_all_ae
#print axioms ProbabilityTheory.tendstoUniformly_empiricalCDFSequence_ae
#print axioms ProbabilityTheory.tendstoUniformly_empiricalCDFSequence_ae_of_continuous_cdf
#print axioms MeasureTheory.tendstoLocallyInMeasure_of_tendsto_ae
#print axioms MeasureTheory.tendstoInMeasure_iff_tendsto_truncatedDist_integral
#print axioms MeasureTheory.tendstoLocallyInMeasure_iff_spanning
#print axioms MeasureTheory.localConvergencePseudodist_tendsto_iff
#print axioms MeasureTheory.AEEqFun.localConvergenceDist_eq_zero_imp
#print axioms MeasureTheory.AEEqFun.tendsto_iff_tendstoLocallyInMeasure
#print axioms MeasureTheory.tendsto_ae_of_summable_measure_edist_local
#print axioms MeasureTheory.exists_stronglyMeasurable_tendsto_ae_of_fast_cauchy_local
#print axioms MeasureTheory.CauchyLocallyInMeasure.exists_tendsto
#print axioms MeasureTheory.cauchyLocallyInMeasure_iff_exists_tendsto
#print axioms MeasureTheory.TendstoLocallyInMeasure.exists_seq_tendsto_ae_restrict
#print axioms MeasureTheory.TendstoLocallyInMeasure.exists_seq_tendsto_ae
#print axioms MeasureTheory.exists_seq_tendstoLocallyInMeasure_atTop_iff
#print axioms MeasureTheory.unifIntegrable_of_superlinearEnvelope
#print axioms MeasureTheory.uniformIntegrable_of_superlinearEnvelope
#print axioms MeasureTheory.TendstoLocallyInMeasure.tendsto_eLpNorm_restrict
