import StochLean.Probability.LimitTheorems.SemanticRegression
import StochLean.Probability.InfinitelyDivisible.SemanticRegression
import StochLean.Probability.Brownian.SemanticRegression

/-! Focused axiom checks for the newer foundation modules. -/

#print axioms ProbabilityTheory.variance_triangularRowSum_eq_sum
#print axioms ProbabilityTheory.variance_triangularRowSum_eq_one
#print axioms ProbabilityTheory.isNullArray_iff_eventual
#print axioms ProbabilityTheory.satisfiesLindeberg_iff_unit
#print axioms ProbabilityTheory.SatisfiesUnitLindeberg.isNullArray
#print axioms ProbabilityTheory.SatisfiesLindeberg.isNullArray
#print axioms ProbabilityTheory.SatisfiesLyapunovDeltaAtScale.satisfiesLindebergAtScale
#print axioms ProbabilityTheory.SatisfiesLindeberg.tendsto_map_triangularRowSum_standardGaussian
#print axioms ProbabilityTheory.threeSeriesTruncation_eq_indicator
#print axioms ProbabilityTheory.orderedRandomSeriesConvergesAE_of_variance_tsum_lt_top
#print axioms ProbabilityTheory.kolmogorovThreeSeries_iff
#print axioms ProbabilityTheory.tendstoInDistribution_normalizedVectorPartialSum
#print axioms MeasureTheory.ProbabilityMeasure.convPow_add
#print axioms ProbabilityTheory.IsConvolutionSemigroup.isInfinitelyDivisible
#print axioms ProbabilityTheory.IsConvolutionSemigroup.convPow_root
#print axioms ProbabilityTheory.IsContinuousConvolutionSemigroup.roots_tendsto_zero
#print axioms ProbabilityTheory.HasStationaryIndependentIncrements.isConvolutionSemigroup
#print axioms ProbabilityTheory.HasStationaryIndependentIncrements.incrementLaw_isInfinitelyDivisible
#print axioms ProbabilityTheory.CompoundPoisson.law_zero
#print axioms ProbabilityTheory.CompoundPoisson.ofFiniteMeasure_zero
#print axioms ProbabilityTheory.CompoundPoisson.ofFiniteMeasure_smul_probability
#print axioms ProbabilityTheory.CompoundPoisson.law_add
#print axioms ProbabilityTheory.CompoundPoisson.isInfinitelyDivisible
#print axioms ProbabilityTheory.IsLevyMeasure.sigmaFinite
#print axioms ProbabilityTheory.isLevyMeasure_geometricLevyMeasure
#print axioms ProbabilityTheory.geometricLevyMeasure_univ
#print axioms ProbabilityTheory.LevyTriplet.exists_represents
#print axioms ProbabilityTheory.LevyTriplet.isInfinitelyDivisible_iff_exists_representingTriplet
#print axioms ProbabilityTheory.nonnegativeLevyKhintchine_iff
#print axioms ProbabilityTheory.charFun_ne_zero_of_tendsto_infinitelyDivisible
#print axioms MeasureTheory.ProbabilityMeasure.convPow_affineMap
#print axioms MeasureTheory.ProbabilityMeasure.IsStableInBroadSense.isInfinitelyDivisible
#print axioms MeasureTheory.ProbabilityMeasure.IsStableInBroadSenseWithIndex.isStableInBroadSense
#print axioms MeasureTheory.ProbabilityMeasure.IsStableInBroadSenseWithIndex.shift_isStableWithIndex
#print axioms MeasureTheory.ProbabilityMeasure.IsStableInBroadSenseWithIndex.one_isStableWithIndex_of_logCenter
#print axioms MeasureTheory.ProbabilityMeasure.IsStableWithIndex.isStable
#print axioms ProbabilityTheory.IsStableInBroadSenseWithIndex.index_le_two
#print axioms ProbabilityTheory.IsStableInBroadSenseWithIndex.exists_triplet_gaussianDichotomy
#print axioms ProbabilityTheory.IsStableInBroadSense.exists_index
#print axioms ProbabilityTheory.IsStableInBroadSenseWithIndex.eq_gaussianLaw_of_index_two
#print axioms ProbabilityTheory.IsStableInBroadSenseWithIndex.exists_jump_classification_of_index_lt_two
#print axioms ProbabilityTheory.continuous_stableExponentAtOne
#print axioms ProbabilityTheory.LevyTriplet.exponent_affine_one_ne
#print axioms ProbabilityTheory.isInfinitelyDivisible_of_tendsto
#print axioms MeasureTheory.ProbabilityMeasure.IsInfinitelyDivisible.eq_pointMass_of_boundedSupport
#print axioms ProbabilityTheory.IsPreBrownianReal.timeInversion
#print axioms ProbabilityTheory.IsPreBrownianReal.hasStationaryIndependentIncrements
#print axioms ProbabilityTheory.IsPreBrownianReal.brownianIncrementLaw_isInfinitelyDivisible
#print axioms ProbabilityTheory.IsPreBrownianReal.brownianBridge_isGaussianProcess
#print axioms ProbabilityTheory.IsPreBrownianReal.integral_brownianBridge
#print axioms ProbabilityTheory.IsPreBrownianReal.covariance_brownianBridge
#print axioms ProbabilityTheory.IsPreBrownianReal.hasLaw_brownianBridge
#print axioms ProbabilityTheory.BrownianReal.isBrownianReal_brownianCoordinate
#print axioms ProbabilityTheory.IsBrownianReal.ae_locallyHolder_lt_half
#print axioms ProbabilityTheory.IsPreBrownianReal.ae_nowhere_hasFiniteDerivativeAt
#print axioms ProbabilityTheory.IsBrownianReal.condExp_futureIncrementsAfter
#print axioms ProbabilityTheory.IsBrownianReal.reflection_principle
#print axioms ProbabilityTheory.IsBrownianReal.lastZeroBefore_cdf
#print axioms ProbabilityTheory.IsBrownianReal.blumenthal_zeroOne_canonical
#print axioms ProbabilityTheory.IsPreBrownianReal.norm_deterministicWienerIntegral
#print axioms ProbabilityTheory.IsGaussianProcess.isPreBrownianReal_of_covariance
