/-
Copyright (c) 2026 StochLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: StochLean contributors
-/
module

public import Mathlib.MeasureTheory.Measure.LevyConvergence
public import StochLean.Probability.InfinitelyDivisible.LevyKhintchine

/-!
# Convolution semigroups generated by Lévy triplets

This module isolates the algebraic and continuity part of the Lévy--Khintchine-to-process bridge.
Existence of the laws with scaled exponents is an explicit hypothesis; once such laws are
available, their semigroup property and weak continuity are consequences rather than stored data.
-/

@[expose] public section

open Filter MeasureTheory
open scoped ENNReal NNReal Topology

namespace ProbabilityTheory

namespace LevyTriplet

/-- `ν t` is represented by the triplet obtained by scaling `η` by nonnegative time `t`. -/
def HasScaledLaws (η : LevyTriplet) (ν : ℝ≥0 → ProbabilityMeasure ℝ) : Prop :=
  ∀ t, (η.nnrealSMul t).Represents (ν t)

theorem HasScaledLaws.isConvolutionSemigroup {η : LevyTriplet}
    {ν : ℝ≥0 → ProbabilityMeasure ℝ} (hν : η.HasScaledLaws ν) :
    IsConvolutionSemigroup ν := by
  intro s t
  apply ProbabilityMeasure.toMeasure_injective
  apply Measure.ext_of_charFun
  funext u
  rw [ProbabilityMeasure.coe_conv, charFun_conv, hν (s + t) u, hν s u, hν t u,
    ← Complex.exp_add, ← exponent_add, ← nnrealSMul_add]

theorem HasScaledLaws.continuous {η : LevyTriplet}
    {ν : ℝ≥0 → ProbabilityMeasure ℝ} (hν : η.HasScaledLaws ν) : Continuous ν := by
  rw [continuous_iff_seqContinuous]
  intro u t hut
  apply ProbabilityMeasure.tendsto_of_tendsto_charFun
  intro z
  have hcontinuous : Continuous
      (fun r : ℝ≥0 => Complex.exp ((r : ℂ) * η.exponent z)) := by fun_prop
  have htend := hcontinuous.continuousAt.tendsto.comp hut
  change Tendsto (fun n => Complex.exp (((u n : ℝ≥0) : ℂ) * η.exponent z)) atTop
    (𝓝 (Complex.exp ((t : ℂ) * η.exponent z))) at htend
  change Tendsto (fun n => charFun (ν (u n) : Measure ℝ) z) atTop
    (𝓝 (charFun (ν t : Measure ℝ) z))
  simpa only [hν _ z, exponent_nnrealSMul] using htend

theorem HasScaledLaws.zero_eq_pointMass {η : LevyTriplet}
    {ν : ℝ≥0 → ProbabilityMeasure ℝ} (hν : η.HasScaledLaws ν) :
    ν 0 = ProbabilityMeasure.pointMass 0 := by
  apply ProbabilityMeasure.toMeasure_injective
  apply Measure.ext_of_charFun
  funext t
  rw [hν 0 t, nnrealSMul_zero, exponent_zeroTriplet,
    ProbabilityMeasure.coe_pointMass, charFun_dirac]
  simp

theorem HasScaledLaws.isContinuousConvolutionSemigroup {η : LevyTriplet}
    {ν : ℝ≥0 → ProbabilityMeasure ℝ} (hν : η.HasScaledLaws ν) :
    IsContinuousConvolutionSemigroup ν := by
  refine ⟨hν.isConvolutionSemigroup, ?_⟩
  rw [← hν.zero_eq_pointMass]
  exact hν.continuous.continuousAt.mono_left inf_le_left

/-- Choice of a scaled law from pointwise Lévy--Khintchine existence. -/
noncomputable def scaledLaw (η : LevyTriplet)
    (hexists : ∀ t : ℝ≥0, ∃ μ : ProbabilityMeasure ℝ, (η.nnrealSMul t).Represents μ)
    (t : ℝ≥0) : ProbabilityMeasure ℝ :=
  Classical.choose (hexists t)

theorem hasScaledLaws_scaledLaw (η : LevyTriplet)
    (hexists : ∀ t : ℝ≥0, ∃ μ : ProbabilityMeasure ℝ, (η.nnrealSMul t).Represents μ) :
    η.HasScaledLaws (η.scaledLaw hexists) :=
  fun t => Classical.choose_spec (hexists t)

theorem exists_continuousConvolutionSemigroup
    (η : LevyTriplet)
    (hexists : ∀ t : ℝ≥0, ∃ μ : ProbabilityMeasure ℝ, (η.nnrealSMul t).Represents μ) :
    ∃ ν : ℝ≥0 → ProbabilityMeasure ℝ,
      IsContinuousConvolutionSemigroup ν ∧ η.HasScaledLaws ν := by
  refine ⟨η.scaledLaw hexists, ?_, hasScaledLaws_scaledLaw η hexists⟩
  exact (hasScaledLaws_scaledLaw η hexists).isContinuousConvolutionSemigroup

/-- Staged Corollary 16.10: a represented law lies at time one of the continuous semigroup once
existence is known for every nonnegative scaling of its triplet. -/
theorem exists_continuousConvolutionSemigroup_through
    {μ : ProbabilityMeasure ℝ} (η : LevyTriplet) (hη : η.Represents μ)
    (hexists : ∀ t : ℝ≥0, ∃ ρ : ProbabilityMeasure ℝ, (η.nnrealSMul t).Represents ρ) :
    ∃ ν : ℝ≥0 → ProbabilityMeasure ℝ,
      IsContinuousConvolutionSemigroup ν ∧ ν 1 = μ := by
  let ν := η.scaledLaw hexists
  have hscaled : η.HasScaledLaws ν := hasScaledLaws_scaledLaw η hexists
  refine ⟨ν, hscaled.isContinuousConvolutionSemigroup, ?_⟩
  apply ProbabilityMeasure.toMeasure_injective
  apply Measure.ext_of_charFun
  funext t
  rw [hscaled 1 t, nnrealSMul_one, hη t]

end LevyTriplet

namespace CompoundPoisson

/-- The compound Poisson laws with linearly scaled intensity are exactly the scaled-law family of
their fixed-truncation triplet. -/
theorem hasScaledLaws (r : ℝ≥0) (μ : ProbabilityMeasure ℝ)
    (hzero : (μ : Measure ℝ) {0} = 0) :
    (triplet r μ hzero).HasScaledLaws (fun t => law (t * r) μ) := by
  intro t z
  rw [charFun_law, LevyTriplet.exponent_nnrealSMul, exponent_triplet]
  congr 1
  push_cast
  ring

theorem isContinuousConvolutionSemigroup_mul (r : ℝ≥0) (μ : ProbabilityMeasure ℝ)
    (hzero : (μ : Measure ℝ) {0} = 0) :
    IsContinuousConvolutionSemigroup (fun t => law (t * r) μ) :=
  (hasScaledLaws r μ hzero).isContinuousConvolutionSemigroup

end CompoundPoisson

end ProbabilityTheory
