/-
Copyright (c) 2026 StochLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: StochLean contributors
-/
module

public import StochLean.Probability.InfinitelyDivisible.LevySemigroup
public import StochLean.Probability.Process.StationaryIndependentIncrementsFiniteLaws

/-!
# Coordinate processes generated by real Lévy triplets

The law family generated by scaling a project-local Lévy triplet is fed into the project-local
Kolmogorov construction.  This is a law-level Lévy-process realization: it supplies genuine
stationary independent increments, but deliberately asserts no path regularity.
-/

@[expose] public section

open MeasureTheory
open scoped ENNReal NNReal MeasureTheory ProbabilityTheory

namespace ProbabilityTheory.LevyTriplet

/-- The canonical product-space measure carrying the coordinate process generated by `η`. -/
noncomputable def coordinateMeasure (η : LevyTriplet) : Measure (ℝ≥0 → ℝ) :=
  SIIConstruction.coordinateMeasureOfSemigroup η.canonicalScaledLaw
    η.isContinuousConvolutionSemigroup_canonicalScaledLaw.isConvolutionSemigroup

instance coordinateMeasure.instIsProbabilityMeasure (η : LevyTriplet) :
    IsProbabilityMeasure η.coordinateMeasure := by
  unfold coordinateMeasure
  infer_instance

instance coordinateMeasure.instIsFiniteMeasure (η : LevyTriplet) :
    IsFiniteMeasure η.coordinateMeasure := by infer_instance

/-- The canonical coordinate process has the full finite product laws generated by `η`. -/
theorem hasFiniteStationaryIncrementLaws_coordinateProcess (η : LevyTriplet) :
    HasFiniteStationaryIncrementLaws SIIConstruction.coordinateProcess η.canonicalScaledLaw
      η.coordinateMeasure := by
  exact SIIConstruction.hasFiniteStationaryIncrementLaws_coordinateProcess
    η.canonicalScaledLaw
    η.isContinuousConvolutionSemigroup_canonicalScaledLaw.isConvolutionSemigroup

/-- The canonical coordinate process generated by a triplet has stationary independent
increments. -/
theorem hasStationaryIndependentIncrements_coordinateProcess (η : LevyTriplet) :
    HasStationaryIndependentIncrements SIIConstruction.coordinateProcess η.coordinateMeasure :=
  (η.hasFiniteStationaryIncrementLaws_coordinateProcess).hasStationaryIndependentIncrements

/-- The time-one increment of the canonical coordinate process has the canonical law of `η`. -/
theorem hasLaw_coordinateProcess_one_sub_zero (η : LevyTriplet) :
    HasLaw
      (fun ω => SIIConstruction.coordinateProcess 1 ω -
        SIIConstruction.coordinateProcess 0 ω)
      η.law η.coordinateMeasure := by
  have h := SIIConstruction.hasIncrementLawFamily_coordinateProcess
    η.canonicalScaledLaw
    η.isContinuousConvolutionSemigroup_canonicalScaledLaw.isConvolutionSemigroup 1
  rw [η.canonicalScaledLaw_one_eq_of_represents η.represents_law] at h
  exact h

/-- Every represented law occurs as the time-one increment law of a canonical product-space SII
process. -/
theorem Represents.exists_coordinateProcess
    {η : LevyTriplet} {μ : ProbabilityMeasure ℝ} (hη : η.Represents μ) :
    ∃ P : Measure (ℝ≥0 → ℝ), IsProbabilityMeasure P ∧
      HasStationaryIndependentIncrements SIIConstruction.coordinateProcess P ∧
      HasLaw
        (fun ω => SIIConstruction.coordinateProcess 1 ω -
          SIIConstruction.coordinateProcess 0 ω) μ P := by
  refine ⟨η.coordinateMeasure, inferInstance,
    η.hasStationaryIndependentIncrements_coordinateProcess, ?_⟩
  have h := η.hasLaw_coordinateProcess_one_sub_zero
  rw [← η.canonicalScaledLaw_one_eq_of_represents hη,
    η.canonicalScaledLaw_one_eq_of_represents η.represents_law]
  exact h

end ProbabilityTheory.LevyTriplet
