/-
Copyright (c) 2026 StochLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: StochLean contributors
-/
module

public import StochLean.Probability.InfinitelyDivisible.ContinuousPowers
public import StochLean.Probability.Process.StationaryIndependentIncrementsFiniteLaws

/-!
# Stationary-independent-increment processes from infinitely divisible laws

Every real infinitely divisible law generates an internal continuous convolution semigroup.  This
module feeds that semigroup into the project-local Kolmogorov construction and realizes the given
law as the time-one increment of a genuine stationary-independent-increment coordinate process.
No path-regularity assertion is bundled into this construction.
-/

@[expose] public section

open MeasureTheory
open scoped ENNReal NNReal MeasureTheory ProbabilityTheory

namespace MeasureTheory.ProbabilityMeasure.IsInfinitelyDivisible

/-- The canonical product-space probability measure generated by an infinitely divisible law. -/
noncomputable def coordinateMeasure {μ : ProbabilityMeasure ℝ}
    (hμ : μ.IsInfinitelyDivisible) : Measure (ℝ≥0 → ℝ) :=
  ProbabilityTheory.SIIConstruction.coordinateMeasureOfSemigroup hμ.positivePower
    hμ.isConvolutionSemigroup_positivePower

instance coordinateMeasure.instIsProbabilityMeasure {μ : ProbabilityMeasure ℝ}
    (hμ : μ.IsInfinitelyDivisible) : IsProbabilityMeasure hμ.coordinateMeasure := by
  unfold coordinateMeasure
  infer_instance

instance coordinateMeasure.instIsFiniteMeasure {μ : ProbabilityMeasure ℝ}
    (hμ : μ.IsInfinitelyDivisible) : IsFiniteMeasure hμ.coordinateMeasure := by
  infer_instance

/-- The canonical coordinate process has all finite increment laws prescribed by the continuous
positive powers of the original law. -/
theorem hasFiniteStationaryIncrementLaws_coordinateProcess {μ : ProbabilityMeasure ℝ}
    (hμ : μ.IsInfinitelyDivisible) :
    ProbabilityTheory.HasFiniteStationaryIncrementLaws
      ProbabilityTheory.SIIConstruction.coordinateProcess hμ.positivePower hμ.coordinateMeasure :=
  ProbabilityTheory.SIIConstruction.hasFiniteStationaryIncrementLaws_coordinateProcess
    hμ.positivePower hμ.isConvolutionSemigroup_positivePower

/-- The canonical coordinate process has stationary independent increments. -/
theorem hasStationaryIndependentIncrements_coordinateProcess {μ : ProbabilityMeasure ℝ}
    (hμ : μ.IsInfinitelyDivisible) :
    ProbabilityTheory.HasStationaryIndependentIncrements
      ProbabilityTheory.SIIConstruction.coordinateProcess hμ.coordinateMeasure :=
  hμ.hasFiniteStationaryIncrementLaws_coordinateProcess.hasStationaryIndependentIncrements

/-- The time-one increment of the canonical process has the original infinitely divisible law. -/
theorem hasLaw_coordinateProcess_one_sub_zero {μ : ProbabilityMeasure ℝ}
    (hμ : μ.IsInfinitelyDivisible) :
    ProbabilityTheory.HasLaw
      (fun ω => ProbabilityTheory.SIIConstruction.coordinateProcess 1 ω -
        ProbabilityTheory.SIIConstruction.coordinateProcess 0 ω)
      μ hμ.coordinateMeasure := by
  have h := ProbabilityTheory.SIIConstruction.hasIncrementLawFamily_coordinateProcess
    hμ.positivePower hμ.isConvolutionSemigroup_positivePower 1
  simpa only [coordinateMeasure, hμ.positivePower_one] using h

/-- Corollary 16.10 in process form: every real infinitely divisible law occurs as the time-one
increment law of a stationary-independent-increment process. -/
theorem exists_stationaryIndependentIncrements_process {μ : ProbabilityMeasure ℝ}
    (hμ : μ.IsInfinitelyDivisible) :
    ∃ P : Measure (ℝ≥0 → ℝ), IsProbabilityMeasure P ∧
      ProbabilityTheory.HasStationaryIndependentIncrements
        ProbabilityTheory.SIIConstruction.coordinateProcess P ∧
      ProbabilityTheory.HasLaw
        (fun ω => ProbabilityTheory.SIIConstruction.coordinateProcess 1 ω -
          ProbabilityTheory.SIIConstruction.coordinateProcess 0 ω)
        μ P :=
  ⟨hμ.coordinateMeasure, inferInstance,
    hμ.hasStationaryIndependentIncrements_coordinateProcess,
    hμ.hasLaw_coordinateProcess_one_sub_zero⟩

end MeasureTheory.ProbabilityMeasure.IsInfinitelyDivisible
