/-
Copyright (c) 2026 StochLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: StochLean contributors
-/
module

public import StochLean.Probability.Exchangeability.SigmaFields

/-!
# Future sigma-fields of a process

This file owns the generic future information generated by a process.  It is deliberately not a
Markov-specific construction.  For `X : T → Ω → E`, `futureMeasurableSpace X t` is generated by
the coordinates `X s` with `t ≤ s`.
-/

@[expose] public section

open MeasureTheory

namespace ProbabilityTheory

variable {T Ω E : Type*} [Preorder T] [MeasurableSpace Ω] [MeasurableSpace E]

/-- The sigma-field generated by the coordinates of `X` at and after time `t`. -/
@[instance_reducible]
def futureMeasurableSpace (X : T → Ω → E) (t : T) : MeasurableSpace Ω :=
  ⨆ s : {s : T // t ≤ s}, MeasurableSpace.comap (X s) inferInstance

omit [MeasurableSpace Ω] in
/-- The coordinate at the current time is measurable with respect to the future sigma-field. -/
theorem measurableSpace_comap_le_futureMeasurableSpace (X : T → Ω → E) (t : T) :
    MeasurableSpace.comap (X t) inferInstance ≤ futureMeasurableSpace X t := by
  exact le_iSup_of_le ⟨t, le_rfl⟩ le_rfl

omit [MeasurableSpace Ω] in
/-- Every current coordinate is measurable for the corresponding future sigma-field. -/
theorem measurable_futureMeasurableSpace (X : T → Ω → E) (t : T) :
    @Measurable Ω E (futureMeasurableSpace X t) inferInstance (X t) := by
  exact measurable_iff_comap_le.mpr (measurableSpace_comap_le_futureMeasurableSpace X t)

omit [MeasurableSpace Ω] in
/-- Future information decreases as the initial time increases. -/
theorem futureMeasurableSpace_antitone (X : T → Ω → E) :
    Antitone (futureMeasurableSpace X) := by
  intro s t hst
  refine iSup_le fun u => ?_
  exact le_iSup_of_le ⟨u, hst.trans u.property⟩ le_rfl

omit [MeasurableSpace Ω] in
/-- Minimality of the future sigma-field among sigma-fields making all future coordinates
measurable. -/
theorem futureMeasurableSpace_le
    (X : T → Ω → E) (t : T) (m : MeasurableSpace Ω)
    (hX : ∀ s, t ≤ s → @Measurable Ω E m inferInstance (X s)) :
    futureMeasurableSpace X t ≤ m := by
  refine iSup_le fun s => ?_
  exact measurable_iff_comap_le.mp (hX s s.property)

/-- On canonical sequence space, future information agrees with the already established tail
sigma-field starting at `n`. -/
theorem futureMeasurableSpace_coordinate_eq_tailFromMeasurableSpace (n : ℕ) :
    futureMeasurableSpace (fun k (x : ℕ → E) => x k) n =
      tailFromMeasurableSpace (E := E) n :=
  rfl

/-- The canonical tail sigma-field is the intersection of all future sigma-fields. -/
theorem tailMeasurableSpace_eq_iInf_futureMeasurableSpace :
    tailMeasurableSpace (E := E) =
      ⨅ n : ℕ, futureMeasurableSpace (fun k (x : ℕ → E) => x k) n :=
  rfl

end ProbabilityTheory
