name = "stochlean"
version = "0.1.0"
keywords = ["mathematics", "probability", "stochastic-processes", "lean"]
defaultTargets = ["StochLean"]

[leanOptions]
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.33.0"

[[require]]
name = "exchangeability"
git = "https://github.com/cameronfreer/exchangeability.git"
rev = "e0532e59ceff23edab44dda9ab0655debbc9cc22"

[[lean_lib]]
name = "StochLean"
weakLeanArgs = ["--memory=24000", "--threads=3"]
