/-
Copyright (c) 2026 StochLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: StochLean contributors
-/
module

public import Mathlib.Data.Real.Basic
public import Mathlib.Data.Finset.Card
public import Mathlib.Data.Fintype.Card

/-!
# Empirical cumulative distribution functions

Samples are indexed by `Fin (n + 1)`, so the denominator is intrinsically nonzero. This avoids
giving an artificial probability interpretation to the empty-sample case.
-/

@[expose] public section

open Finset

namespace ProbabilityTheory

noncomputable section

/-- The empirical CDF of a nonempty finite real sample. -/
def empiricalCDF {n : ℕ} (x : Fin (n + 1) → ℝ) (t : ℝ) : ℝ :=
  ((univ.filter fun i ↦ x i ≤ t).card : ℝ) / ((n + 1 : ℕ) : ℝ)

lemma empiricalCDF_nonneg {n : ℕ} (x : Fin (n + 1) → ℝ) (t : ℝ) :
    0 ≤ empiricalCDF x t := by
  exact div_nonneg (Nat.cast_nonneg _) (Nat.cast_nonneg _)

lemma empiricalCDF_le_one {n : ℕ} (x : Fin (n + 1) → ℝ) (t : ℝ) :
    empiricalCDF x t ≤ 1 := by
  have hden : (0 : ℝ) < ((n + 1 : ℕ) : ℝ) := by
    exact_mod_cast Nat.succ_pos n
  rw [empiricalCDF, div_le_one hden]
  exact_mod_cast card_finset_fin_le (univ.filter fun i ↦ x i ≤ t)

lemma empiricalCDF_mem_unitInterval {n : ℕ} (x : Fin (n + 1) → ℝ) (t : ℝ) :
    empiricalCDF x t ∈ Set.Icc (0 : ℝ) 1 :=
  ⟨empiricalCDF_nonneg x t, empiricalCDF_le_one x t⟩

/-- An empirical CDF is monotone in its threshold. -/
lemma monotone_empiricalCDF {n : ℕ} (x : Fin (n + 1) → ℝ) :
    Monotone (empiricalCDF x) := by
  intro s t hst
  unfold empiricalCDF
  have hden : (0 : ℝ) < ((n + 1 : ℕ) : ℝ) := by
    exact_mod_cast Nat.succ_pos n
  rw [div_le_div_iff_of_pos_right hden]
  exact_mod_cast card_le_card (by
    intro i hi
    simp only [mem_filter, mem_univ, true_and] at hi ⊢
    exact hi.trans hst)

lemma empiricalCDF_eq_zero_of_lt {n : ℕ} (x : Fin (n + 1) → ℝ) (t : ℝ)
    (h : ∀ i, t < x i) : empiricalCDF x t = 0 := by
  have hf : (univ.filter fun i ↦ x i ≤ t) = ∅ := by
    apply filter_eq_empty_iff.mpr
    intro i _
    exact not_le.mpr (h i)
  simp [empiricalCDF, hf]

lemma empiricalCDF_eq_one_of_le {n : ℕ} (x : Fin (n + 1) → ℝ) (t : ℝ)
    (h : ∀ i, x i ≤ t) : empiricalCDF x t = 1 := by
  have hf : (univ.filter fun i ↦ x i ≤ t) = univ :=
    filter_eq_self.mpr fun i _ ↦ h i
  rw [empiricalCDF, hf, card_fin]
  exact div_self (by
    exact_mod_cast (Nat.succ_ne_zero n))

/-- The empirical CDF process generated by the first `n + 1` observations of a sequence. -/
def empiricalCDFSequence {Ω : Type*} (X : ℕ → Ω → ℝ) (n : ℕ) (ω : Ω) (t : ℝ) : ℝ :=
  empiricalCDF (fun i : Fin (n + 1) ↦ X i ω) t

lemma empiricalCDFSequence_nonneg {Ω : Type*} (X : ℕ → Ω → ℝ)
    (n : ℕ) (ω : Ω) (t : ℝ) : 0 ≤ empiricalCDFSequence X n ω t :=
  empiricalCDF_nonneg _ _

lemma empiricalCDFSequence_le_one {Ω : Type*} (X : ℕ → Ω → ℝ)
    (n : ℕ) (ω : Ω) (t : ℝ) : empiricalCDFSequence X n ω t ≤ 1 :=
  empiricalCDF_le_one _ _

lemma monotone_empiricalCDFSequence {Ω : Type*} (X : ℕ → Ω → ℝ) (n : ℕ) (ω : Ω) :
    Monotone (empiricalCDFSequence X n ω) :=
  monotone_empiricalCDF _

end

end ProbabilityTheory
