/-
Copyright (c) 2026 StochLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: StochLean contributors
-/
module

public import Mathlib.Data.Real.Basic
public import Mathlib.Data.Finset.Card
public import Mathlib.Data.Fintype.Card
public import Mathlib.Algebra.BigOperators.Ring.Finset

/-!
# Empirical cumulative distribution functions

Samples are indexed by `Fin (n + 1)`, so the denominator is intrinsically nonzero. This avoids
giving an artificial probability interpretation to the empty-sample case.
-/

@[expose] public section

open Finset

namespace ProbabilityTheory

noncomputable section

/-- The empirical CDF of a nonempty finite real sample. -/
def empiricalCDF {n : ℕ} (x : Fin (n + 1) → ℝ) (t : ℝ) : ℝ :=
  ((univ.filter fun i ↦ x i ≤ t).card : ℝ) / ((n + 1 : ℕ) : ℝ)

/-- The strict empirical CDF of a nonempty finite real sample. It records the proportion of
observations in `Set.Iio t`; keeping this companion to `empiricalCDF` makes jumps explicit. -/
def empiricalCDFLt {n : ℕ} (x : Fin (n + 1) → ℝ) (t : ℝ) : ℝ :=
  ((univ.filter fun i ↦ x i < t).card : ℝ) / ((n + 1 : ℕ) : ℝ)

/-- Strict and non-strict empirical CDFs are related by reflection and complementation. -/
lemma empiricalCDFLt_eq_one_sub_reflect {n : ℕ} (x : Fin (n + 1) → ℝ) (t : ℝ) :
    empiricalCDFLt x t = 1 - empiricalCDF (fun i ↦ -x i) (-t) := by
  have hpart : (univ.filter fun i ↦ x i < t).card +
      (univ.filter fun i ↦ t ≤ x i).card = n + 1 := by
    rw [← card_union_of_disjoint]
    · rw [← filter_or, filter_eq_self.mpr]
      · exact card_fin (n + 1)
      · intro i _
        exact lt_or_ge (x i) t
    · rw [disjoint_left]
      intro i hi hj
      simp only [mem_filter, mem_univ, true_and] at hi hj
      exact (not_le_of_gt hi) hj
  rw [empiricalCDFLt, empiricalCDF]
  rw [eq_sub_iff_add_eq, ← add_div]
  apply (div_eq_iff (by exact_mod_cast Nat.succ_ne_zero n : ((n + 1 : ℕ) : ℝ) ≠ 0)).2
  norm_num
  exact_mod_cast hpart

/-- An empirical CDF is the average of the corresponding lower-half-line indicators. -/
lemma empiricalCDF_eq_average_indicator {n : ℕ} (x : Fin (n + 1) → ℝ) (t : ℝ) :
    empiricalCDF x t =
      ((n + 1 : ℕ) : ℝ)⁻¹ * ∑ i, Set.indicator (Set.Iic t) (fun _ ↦ (1 : ℝ)) (x i) := by
  rw [empiricalCDF, div_eq_inv_mul]
  congr 1
  simpa only [Set.indicator_apply, Set.mem_Iic, Finset.sum_ite_irrel,
    Finset.sum_const_zero, add_zero] using
    (Finset.natCast_card_filter (R := ℝ) (fun i : Fin (n + 1) ↦ x i ≤ t) Finset.univ)

lemma empiricalCDF_nonneg {n : ℕ} (x : Fin (n + 1) → ℝ) (t : ℝ) :
    0 ≤ empiricalCDF x t := by
  exact div_nonneg (Nat.cast_nonneg _) (Nat.cast_nonneg _)

lemma empiricalCDF_le_one {n : ℕ} (x : Fin (n + 1) → ℝ) (t : ℝ) :
    empiricalCDF x t ≤ 1 := by
  have hden : (0 : ℝ) < ((n + 1 : ℕ) : ℝ) := by
    exact_mod_cast Nat.succ_pos n
  rw [empiricalCDF, div_le_one hden]
  exact_mod_cast card_finset_fin_le (univ.filter fun i ↦ x i ≤ t)

lemma empiricalCDF_mem_unitInterval {n : ℕ} (x : Fin (n + 1) → ℝ) (t : ℝ) :
    empiricalCDF x t ∈ Set.Icc (0 : ℝ) 1 :=
  ⟨empiricalCDF_nonneg x t, empiricalCDF_le_one x t⟩

/-- An empirical CDF is monotone in its threshold. -/
lemma monotone_empiricalCDF {n : ℕ} (x : Fin (n + 1) → ℝ) :
    Monotone (empiricalCDF x) := by
  intro s t hst
  unfold empiricalCDF
  have hden : (0 : ℝ) < ((n + 1 : ℕ) : ℝ) := by
    exact_mod_cast Nat.succ_pos n
  rw [div_le_div_iff_of_pos_right hden]
  exact_mod_cast card_le_card (by
    intro i hi
    simp only [mem_filter, mem_univ, true_and] at hi ⊢
    exact hi.trans hst)

/-- A non-strict empirical count below `s` is bounded by the strict empirical count below every
larger threshold `t`. -/
lemma empiricalCDF_le_empiricalCDFLt_of_lt {n : ℕ} (x : Fin (n + 1) → ℝ)
    {s t : ℝ} (hst : s < t) : empiricalCDF x s ≤ empiricalCDFLt x t := by
  unfold empiricalCDF empiricalCDFLt
  have hden : (0 : ℝ) < ((n + 1 : ℕ) : ℝ) := by
    exact_mod_cast Nat.succ_pos n
  rw [div_le_div_iff_of_pos_right hden]
  exact_mod_cast card_le_card (by
    intro i hi
    simp only [mem_filter, mem_univ, true_and] at hi ⊢
    exact hi.trans_lt hst)

lemma empiricalCDF_eq_zero_of_lt {n : ℕ} (x : Fin (n + 1) → ℝ) (t : ℝ)
    (h : ∀ i, t < x i) : empiricalCDF x t = 0 := by
  have hf : (univ.filter fun i ↦ x i ≤ t) = ∅ := by
    apply filter_eq_empty_iff.mpr
    intro i _
    exact not_le.mpr (h i)
  simp [empiricalCDF, hf]

lemma empiricalCDF_eq_one_of_le {n : ℕ} (x : Fin (n + 1) → ℝ) (t : ℝ)
    (h : ∀ i, x i ≤ t) : empiricalCDF x t = 1 := by
  have hf : (univ.filter fun i ↦ x i ≤ t) = univ :=
    filter_eq_self.mpr fun i _ ↦ h i
  rw [empiricalCDF, hf, card_fin]
  exact div_self (by
    exact_mod_cast (Nat.succ_ne_zero n))

/-- The empirical CDF process generated by the first `n + 1` observations of a sequence. -/
def empiricalCDFSequence {Ω : Type*} (X : ℕ → Ω → ℝ) (n : ℕ) (ω : Ω) (t : ℝ) : ℝ :=
  empiricalCDF (fun i : Fin (n + 1) ↦ X i ω) t

/-- The strict empirical CDF process generated by the first `n + 1` observations. -/
def empiricalCDFSequenceLt {Ω : Type*} (X : ℕ → Ω → ℝ) (n : ℕ) (ω : Ω) (t : ℝ) : ℝ :=
  empiricalCDFLt (fun i : Fin (n + 1) ↦ X i ω) t

lemma empiricalCDFSequenceLt_eq_one_sub_reflect {Ω : Type*} (X : ℕ → Ω → ℝ)
    (n : ℕ) (ω : Ω) (t : ℝ) :
    empiricalCDFSequenceLt X n ω t =
      1 - empiricalCDFSequence (fun i ω ↦ -X i ω) n ω (-t) :=
  empiricalCDFLt_eq_one_sub_reflect _ _

lemma empiricalCDFSequence_le_lt_of_lt {Ω : Type*} (X : ℕ → Ω → ℝ)
    (n : ℕ) (ω : Ω) {s t : ℝ} (hst : s < t) :
    empiricalCDFSequence X n ω s ≤ empiricalCDFSequenceLt X n ω t :=
  empiricalCDF_le_empiricalCDFLt_of_lt _ hst

lemma empiricalCDFSequence_nonneg {Ω : Type*} (X : ℕ → Ω → ℝ)
    (n : ℕ) (ω : Ω) (t : ℝ) : 0 ≤ empiricalCDFSequence X n ω t :=
  empiricalCDF_nonneg _ _

lemma empiricalCDFSequence_le_one {Ω : Type*} (X : ℕ → Ω → ℝ)
    (n : ℕ) (ω : Ω) (t : ℝ) : empiricalCDFSequence X n ω t ≤ 1 :=
  empiricalCDF_le_one _ _

lemma monotone_empiricalCDFSequence {Ω : Type*} (X : ℕ → Ω → ℝ) (n : ℕ) (ω : Ω) :
    Monotone (empiricalCDFSequence X n ω) :=
  monotone_empiricalCDF _

end

end ProbabilityTheory
