/-
Copyright (c) 2026 StochLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: StochLean contributors
-/
module

public import StochLean.Probability.Markov.TransitionSystem

/-!
# Markov semigroups

A Markov semigroup is a property of an existing one-parameter family of Mathlib kernels.  It is
not a bundled process or a replacement kernel type.  The composition law follows Mathlib's
orientation: `κ (s + t) = κ t ∘ₖ κ s`.
-/

@[expose] public section

open MeasureTheory
open scoped ENNReal ProbabilityTheory

namespace ProbabilityTheory

variable {T E : Type*} [AddCommMonoid T] [MeasurableSpace E]

/-- The homogeneous Markov semigroup laws for a family of kernels. -/
structure IsMarkovSemigroup (κ : T → Kernel E E) : Prop where
  zero : κ 0 = Kernel.id
  isMarkovKernel : ∀ t, IsMarkovKernel (κ t)
  add : ∀ s t, κ (s + t) = κ t ∘ₖ κ s

namespace IsMarkovSemigroup

variable {κ : T → Kernel E E}

/-- Every member of a Markov semigroup is a Markov kernel. -/
theorem markov (hκ : IsMarkovSemigroup κ) (t : T) : IsMarkovKernel (κ t) :=
  hκ.isMarkovKernel t

/-- Kernels in a homogeneous Markov semigroup commute. -/
theorem comp_comm (hκ : IsMarkovSemigroup κ) (s t : T) :
    κ t ∘ₖ κ s = κ s ∘ₖ κ t := by
  calc
    κ t ∘ₖ κ s = κ (s + t) := (hκ.add s t).symm
    _ = κ (t + s) := by rw [add_comm]
    _ = κ s ∘ₖ κ t := hκ.add t s

/-- Operator-order version of the semigroup law. -/
theorem add_eq_comp (hκ : IsMarkovSemigroup κ) (s t : T) :
    κ (s + t) = κ t ∘ₖ κ s :=
  hκ.add s t

end IsMarkovSemigroup

/-- The discrete semigroup generated by a single kernel. -/
noncomputable def kernelPowers (κ : Kernel E E) (n : ℕ) : Kernel E E :=
  κ ^ n

@[simp]
theorem kernelPowers_zero (κ : Kernel E E) : kernelPowers κ 0 = Kernel.id :=
  rfl

@[simp]
theorem kernelPowers_add (κ : Kernel E E) (m n : ℕ) :
    kernelPowers κ (m + n) = kernelPowers κ n ∘ₖ kernelPowers κ m := by
  simpa only [kernelPowers, Nat.add_comm] using Kernel.pow_add κ n m

set_option linter.style.haveILetI false in
/-- Powers of a Markov kernel remain Markov. -/
theorem isMarkovKernel_pow (κ : Kernel E E) [IsMarkovKernel κ] :
    ∀ n : ℕ, IsMarkovKernel (κ ^ n)
  | 0 => by
      rw [pow_zero]
      change IsMarkovKernel (Kernel.id : Kernel E E)
      infer_instance
  | n + 1 => by
      rw [pow_succ]
      change IsMarkovKernel ((κ ^ n) ∘ₖ κ)
      haveI : IsMarkovKernel (κ ^ n) := isMarkovKernel_pow κ n
      infer_instance

/-- Kernel powers give the canonical discrete-time Markov semigroup. -/
theorem isMarkovSemigroup_kernelPowers (κ : Kernel E E) [IsMarkovKernel κ] :
    IsMarkovSemigroup (kernelPowers κ) where
  zero := rfl
  isMarkovKernel n := by
    dsimp only [kernelPowers]
    exact isMarkovKernel_pow κ n
  add := kernelPowers_add κ

/-- The lawful forward transition system associated with a discrete homogeneous semigroup. -/
noncomputable def natTransitionSystem (κ : ℕ → Kernel E E) : TransitionSystem ℕ E :=
  fun r s _ => κ (s - r)

/-- A discrete homogeneous Markov semigroup produces a general forward transition system without
assigning any meaning to a backward-time pair. -/
theorem IsMarkovSemigroup.isMarkovTransitionSystem_nat
    {κ : ℕ → Kernel E E} (hκ : IsMarkovSemigroup κ) :
    IsMarkovTransitionSystem (natTransitionSystem κ) where
  isMarkovKernel r s hrs := by
    exact hκ.isMarkovKernel (s - r)
  diagonal t := by
    simp [natTransitionSystem, hκ.zero]
  comp := by
    intro r s t hrs hst
    change κ (t - r) = κ (t - s) ∘ₖ κ (s - r)
    rw [← hκ.add]
    congr 1
    symm
    rw [add_comm]
    exact tsub_add_tsub_cancel hst hrs

end ProbabilityTheory
