/-
Copyright (c) 2026 StochLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: StochLean contributors
-/
module

public import StochLean.Probability.Markov.Semigroup
public import StochLean.Probability.Process.Filtration.Future
public import Mathlib.MeasureTheory.Function.ConditionalExpectation.Real
public import Mathlib.MeasureTheory.Function.ConditionalExpectation.Indicator
public import Mathlib.MeasureTheory.Function.ConditionalExpectation.PullOut
public import Mathlib.Probability.Independence.Conditional
public import Mathlib.Probability.Process.Adapted
public import Mathlib.Probability.Process.Stopping

/-!
# Markov semantics and transition representations

`HasMarkovProperty` is kernel-free: it compares conditional expectations with respect to past
information and the current state sigma-field.  A `HasTransitionSystem` is separate representation
data.  In particular, choosing kernels is never part of the semantic definition of Markovness.
-/

@[expose] public section

open MeasureTheory
open scoped ENNReal MeasureTheory ProbabilityTheory

namespace ProbabilityTheory

variable {T Ω E : Type*} [Preorder T] [MeasurableSpace Ω] [MeasurableSpace E]

/-- The sigma-field generated by a single random variable. -/
@[instance_reducible]
def stateMeasurableSpace (Y : Ω → E) : MeasurableSpace Ω :=
  MeasurableSpace.comap Y inferInstance

/-- Real-valued indicator of the event that `Y` lies in `A`. -/
noncomputable def eventIndicator (Y : Ω → E) (A : Set E) : Ω → ℝ :=
  (Y ⁻¹' A).indicator (fun _ => 1)

/-- A finite-dimensional cylinder event, represented in chronological-list form. -/
def markovCylinderEvent (X : T → Ω → E) : List (T × Set E) → Set Ω
  | [] => Set.univ
  | (t, A) :: l => (X t ⁻¹' A) ∩ markovCylinderEvent X l

@[simp]
theorem markovCylinderEvent_nil (X : T → Ω → E) :
    markovCylinderEvent X [] = Set.univ := rfl

@[simp]
theorem markovCylinderEvent_cons (X : T → Ω → E) (t : T) (A : Set E)
    (l : List (T × Set E)) :
    markovCylinderEvent X ((t, A) :: l) =
      (X t ⁻¹' A) ∩ markovCylinderEvent X l := rfl

/-- Measurability of a finite-dimensional cylinder event. -/
theorem measurableSet_markovCylinderEvent {m : MeasurableSpace Ω}
    (X : T → Ω → E) (l : List (T × Set E))
    (hX : ∀ p ∈ l, @Measurable Ω E m inferInstance (X p.1))
    (hl : ∀ p ∈ l, MeasurableSet p.2) :
    @MeasurableSet Ω m (markovCylinderEvent X l) := by
  induction l with
  | nil => simp
  | cons p l ih =>
      rcases p with ⟨t, A⟩
      rw [markovCylinderEvent_cons]
      exact ((hX (t, A) (by simp)) (hl (t, A) (by simp))).inter
        (ih (fun q hq => hX q (by simp [hq])) (fun q hq => hl q (by simp [hq])))

@[simp]
theorem mem_markovCylinderEvent_iff (ω : Ω) (X : T → Ω → E)
    (l : List (T × Set E)) :
    ω ∈ markovCylinderEvent X l ↔ ∀ p ∈ l, X p.1 ω ∈ p.2 := by
  induction l with
  | nil => simp
  | cons p l ih =>
      rcases p with ⟨t, A⟩
      simp [ih]

/-- Cylinder events depend only on the multiset of their coordinate constraints. -/
theorem markovCylinderEvent_eq_of_perm (X : T → Ω → E) {l₁ l₂ : List (T × Set E)}
    (h : l₁.Perm l₂) : markovCylinderEvent X l₁ = markovCylinderEvent X l₂ := by
  ext ω
  simp only [mem_markovCylinderEvent_iff]
  constructor
  · intro hmem p hp
    exact hmem p (h.mem_iff.mpr hp)
  · intro hmem p hp
    exact hmem p (h.mem_iff.mp hp)

@[simp]
theorem markovCylinderEvent_append (X : T → Ω → E)
    (l₁ l₂ : List (T × Set E)) :
    markovCylinderEvent X (l₁ ++ l₂) =
      markovCylinderEvent X l₁ ∩ markovCylinderEvent X l₂ := by
  ext ω
  simp only [mem_markovCylinderEvent_iff, Set.mem_inter_iff, List.mem_append]
  aesop

/-- The finite-dimensional cylinder π-system generating the future sigma-field. -/
def futureCylinderEvents (X : T → Ω → E) (t : T) : Set (Set Ω) :=
  {u | ∃ l : List (T × Set E),
    (∀ p ∈ l, MeasurableSet p.2) ∧
    (∀ p ∈ l, t ≤ p.1) ∧
    markovCylinderEvent X l = u}

/-- Future cylinders form a π-system. -/
theorem isPiSystem_futureCylinderEvents (X : T → Ω → E) (t : T) :
    IsPiSystem (futureCylinderEvents X t) := by
  rintro u ⟨l₁, hl₁m, hl₁t, rfl⟩ v ⟨l₂, hl₂m, hl₂t, rfl⟩ _
  refine ⟨l₁ ++ l₂, ?_, ?_, markovCylinderEvent_append X l₁ l₂⟩
  · intro p hp
    rcases List.mem_append.mp hp with hp | hp
    · exact hl₁m p hp
    · exact hl₂m p hp
  · intro p hp
    rcases List.mem_append.mp hp with hp | hp
    · exact hl₁t p hp
    · exact hl₂t p hp

/-- The future sigma-field is exactly the sigma-field generated by its finite-dimensional
cylinders. -/
theorem generateFrom_futureCylinderEvents_eq (X : T → Ω → E) (t : T) :
    MeasurableSpace.generateFrom (futureCylinderEvents X t) = futureMeasurableSpace X t := by
  apply le_antisymm
  · refine MeasurableSpace.generateFrom_le ?_
    rintro u ⟨l, hlm, hlt, rfl⟩
    apply measurableSet_markovCylinderEvent X l
    · intro p hp
      exact measurable_iff_comap_le.mpr (le_iSup_of_le ⟨p.1, hlt p hp⟩ le_rfl)
    · exact hlm
  · apply futureMeasurableSpace_le X t
    intro s hts
    show @Measurable Ω E (MeasurableSpace.generateFrom (futureCylinderEvents X t))
      inferInstance (X s)
    refine measurable_iff_comap_le.mpr ?_
    rw [MeasurableSpace.comap_eq_generateFrom]
    apply MeasurableSpace.generateFrom_le
    rintro u ⟨A, hA, rfl⟩
    apply MeasurableSpace.measurableSet_generateFrom
    exact ⟨[(s, A)], by simpa using hA, by simp [hts], by simp [markovCylinderEvent]⟩

omit [MeasurableSpace Ω] [MeasurableSpace E] in
@[simp]
theorem eventIndicator_apply_of_mem (Y : Ω → E) (A : Set E) (ω : Ω) (hω : Y ω ∈ A) :
    eventIndicator Y A ω = 1 := by
  simp [eventIndicator, hω]

omit [MeasurableSpace Ω] [MeasurableSpace E] in
@[simp]
theorem eventIndicator_apply_of_not_mem (Y : Ω → E) (A : Set E) (ω : Ω) (hω : Y ω ∉ A) :
    eventIndicator Y A ω = 0 := by
  simp [eventIndicator, hω]

/-- Kernel-free event-form Markov property. -/
structure HasMarkovProperty
    (X : T → Ω → E) (ℱ : Filtration T ‹MeasurableSpace Ω›) (μ : Measure Ω) : Prop where
  adapted : Adapted ℱ X
  condExp_event : ∀ {s t : T}, s ≤ t → ∀ {A : Set E}, MeasurableSet A →
    μ[eventIndicator (X t) A | ℱ s] =ᵐ[μ]
      μ[eventIndicator (X t) A | stateMeasurableSpace (X s)]

namespace HasMarkovProperty

variable {X : T → Ω → E} {ℱ : Filtration T ‹MeasurableSpace Ω›} {μ : Measure Ω}

/-- The current state is measurable in the ambient sample sigma-field. -/
theorem measurable_state (hX : HasMarkovProperty X ℱ μ) (t : T) : Measurable (X t) :=
  hX.adapted.measurable

/-- The event-form equality exposed under a stable project name. -/
theorem event (hX : HasMarkovProperty X ℱ μ) {s t : T} (hst : s ≤ t)
    {A : Set E} (hA : MeasurableSet A) :
    μ[eventIndicator (X t) A | ℱ s] =ᵐ[μ]
      μ[eventIndicator (X t) A | stateMeasurableSpace (X s)] :=
  hX.condExp_event hst hA

/-- The event-form Markov property extends to real-valued constant indicators of every event in
the sigma-field generated by the future state. -/
theorem condExp_indicatorConst (hX : HasMarkovProperty X ℱ μ) {s t : T} (hst : s ≤ t)
    {u : Set Ω} (hu : MeasurableSet[stateMeasurableSpace (X t)] u) (c : ℝ) :
    μ[u.indicator (fun _ => c) | ℱ s] =ᵐ[μ]
      μ[u.indicator (fun _ => c) | stateMeasurableSpace (X s)] := by
  obtain ⟨A, hA, rfl⟩ := MeasurableSpace.measurableSet_comap.mp hu
  have hfun :
      (X t ⁻¹' A).indicator (fun _ => c) = c • eventIndicator (X t) A := by
    funext ω
    by_cases hω : X t ω ∈ A <;> simp [eventIndicator, hω]
  calc
    μ[(X t ⁻¹' A).indicator (fun _ => c) | ℱ s] =ᵐ[μ]
        μ[c • eventIndicator (X t) A | ℱ s] := by rw [hfun]
    _ =ᵐ[μ] c • μ[eventIndicator (X t) A | ℱ s] :=
      condExp_smul c (eventIndicator (X t) A) (ℱ s)
    _ =ᵐ[μ] c • μ[eventIndicator (X t) A | stateMeasurableSpace (X s)] :=
      (hX.event hst hA).const_smul c
    _ =ᵐ[μ] μ[c • eventIndicator (X t) A | stateMeasurableSpace (X s)] :=
      (condExp_smul c (eventIndicator (X t) A) (stateMeasurableSpace (X s))).symm
    _ =ᵐ[μ] μ[(X t ⁻¹' A).indicator (fun _ => c) |
        stateMeasurableSpace (X s)] := by rw [hfun]

/-- The event-form Markov property determines conditional expectations of every integrable
real-valued function measurable with respect to the future state. -/
theorem condExp_of_aestronglyMeasurable_future [IsProbabilityMeasure μ]
    (hX : HasMarkovProperty X ℱ μ) {s t : T} (hst : s ≤ t) {f : Ω → ℝ}
    (hf : Integrable f μ)
    (hfm : AEStronglyMeasurable[stateMeasurableSpace (X t)] f μ) :
    μ[f | ℱ s] =ᵐ[μ] μ[f | stateMeasurableSpace (X s)] := by
  have hFs : ℱ s ≤ ‹MeasurableSpace Ω› := ℱ.le s
  have hstate_s : stateMeasurableSpace (X s) ≤ ‹MeasurableSpace Ω› :=
    measurable_iff_comap_le.mp (hX.measurable_state s)
  have hstate_t : stateMeasurableSpace (X t) ≤ ‹MeasurableSpace Ω› :=
    measurable_iff_comap_le.mp (hX.measurable_state t)
  let Cpast := condExpL1CLM ℝ hFs μ
  let Cstate := condExpL1CLM ℝ hstate_s μ
  have hLp : Cpast (hf.toL1 f) = Cstate (hf.toL1 f) := by
    refine Lp.induction_stronglyMeasurable hstate_t ENNReal.one_ne_top
      (fun g : Ω →₁[μ] ℝ => Cpast g = Cstate g) ?_ ?_ ?_ (hf.toL1 f) ?_
    · intro c u hu hμu
      have hu_ambient : MeasurableSet u := hstate_t u hu
      let g : Ω → ℝ := u.indicator (fun _ => c)
      have hg : Integrable g μ := (integrable_const c).indicator hu_ambient
      have htoL1 : hg.toL1 g = indicatorConstLp 1 hu_ambient hμu.ne c := by
        apply Lp.ext
        exact hg.coeFn_toL1.trans indicatorConstLp_coeFn.symm
      have hraw := hX.condExp_indicatorConst hst hu c
      have hpast := condExp_ae_eq_condExpL1CLM hFs hg
      have hstate := condExp_ae_eq_condExpL1CLM hstate_s hg
      apply Lp.ext
      change Cpast (indicatorConstLp 1 hu_ambient hμu.ne c) =ᵐ[μ]
        Cstate (indicatorConstLp 1 hu_ambient hμu.ne c)
      rw [← htoL1]
      exact hpast.symm.trans (hraw.trans hstate)
    · intro g h _hg _hh _hgm _hhm _hdisj hg_eq hh_eq
      simp only [map_add, hg_eq, hh_eq]
    · exact isClosed_eq (Cpast.continuous.comp continuous_induced_dom)
        (Cstate.continuous.comp continuous_induced_dom)
    · exact hfm.congr hf.coeFn_toL1.symm
  have hpast := condExp_ae_eq_condExpL1CLM hFs hf
  have hstate := condExp_ae_eq_condExpL1CLM hstate_s hf
  rw [Lp.ext_iff] at hLp
  exact hpast.trans (hLp.trans hstate.symm)

/-- Bounded measurable test-function form of the Markov property. -/
theorem condExp_comp_bounded [IsProbabilityMeasure μ]
    (hX : HasMarkovProperty X ℱ μ) {s t : T} (hst : s ≤ t) {f : E → ℝ}
    (hf : Measurable f) (C : ℝ) (hC : ∀ x, ‖f x‖ ≤ C) :
    μ[f ∘ X t | ℱ s] =ᵐ[μ] μ[f ∘ X t | stateMeasurableSpace (X s)] := by
  apply hX.condExp_of_aestronglyMeasurable_future hst
  · refine Integrable.mono' (integrable_const C) (hf.comp (hX.measurable_state t)
      |>.stronglyMeasurable.aestronglyMeasurable) ?_
    filter_upwards [] with ω
    exact hC (X t ω)
  · exact (hf.comp (measurable_iff_comap_le.mpr le_rfl)).stronglyMeasurable.aestronglyMeasurable

/-- A future-event conditional-expectation identity propagates backwards in time. -/
theorem condExp_event_of_later [IsProbabilityMeasure μ]
    (hX : HasMarkovProperty X ℱ μ) {r s : T} (hrs : r ≤ s) {u : Set Ω}
    (hs : μ[u.indicator (fun _ => (1 : ℝ)) | ℱ s] =ᵐ[μ]
      μ[u.indicator (fun _ => (1 : ℝ)) | stateMeasurableSpace (X s)]) :
    μ[u.indicator (fun _ => (1 : ℝ)) | ℱ r] =ᵐ[μ]
      μ[u.indicator (fun _ => (1 : ℝ)) | stateMeasurableSpace (X r)] := by
  let f : Ω → ℝ := u.indicator (fun _ => 1)
  have hFrs : ℱ r ≤ ℱ s := ℱ.mono hrs
  have hstate_r_Fs : stateMeasurableSpace (X r) ≤ ℱ s :=
    (measurable_iff_comap_le.mp (hX.adapted r)).trans hFrs
  have htower_past := condExp_condExp_of_le (f := f) hFrs (ℱ.le s) (μ := μ)
  have htower_state := condExp_condExp_of_le (f := f) hstate_r_Fs (ℱ.le s) (μ := μ)
  have hbridge := hX.condExp_of_aestronglyMeasurable_future hrs
    (f := μ[f | stateMeasurableSpace (X s)]) integrable_condExp
    stronglyMeasurable_condExp.aestronglyMeasurable
  calc
    μ[f | ℱ r] =ᵐ[μ] μ[μ[f | ℱ s] | ℱ r] := htower_past.symm
    _ =ᵐ[μ] μ[μ[f | stateMeasurableSpace (X s)] | ℱ r] := condExp_congr_ae hs
    _ =ᵐ[μ] μ[μ[f | stateMeasurableSpace (X s)] |
        stateMeasurableSpace (X r)] := hbridge
    _ =ᵐ[μ] μ[μ[f | ℱ s] | stateMeasurableSpace (X r)] := condExp_congr_ae hs.symm
    _ =ᵐ[μ] μ[f | stateMeasurableSpace (X r)] := htower_state

/-- Adding a present-state event to an event satisfying the Markov identity at the same time
preserves that identity. -/
theorem condExp_inter_stateEvent [IsProbabilityMeasure μ]
    (hX : HasMarkovProperty X ℱ μ) (t : T) {u v : Set Ω}
    (hu : MeasurableSet[stateMeasurableSpace (X t)] u) (hv : MeasurableSet v)
    (hv_markov : μ[v.indicator (fun _ => (1 : ℝ)) | ℱ t] =ᵐ[μ]
      μ[v.indicator (fun _ => (1 : ℝ)) | stateMeasurableSpace (X t)]) :
    μ[(u ∩ v).indicator (fun _ => (1 : ℝ)) | ℱ t] =ᵐ[μ]
      μ[(u ∩ v).indicator (fun _ => (1 : ℝ)) | stateMeasurableSpace (X t)] := by
  let f : Ω → ℝ := v.indicator (fun _ => 1)
  have hu_ambient : MeasurableSet u :=
    (measurable_iff_comap_le.mp (hX.measurable_state t)) u hu
  have hu_filtration : MeasurableSet[ℱ t] u :=
    (measurable_iff_comap_le.mp (hX.adapted t)) u hu
  have hf : Integrable f μ := (integrable_const (1 : ℝ)).indicator hv
  have hinter : (u ∩ v).indicator (fun _ => (1 : ℝ)) = u.indicator f := by
    funext ω
    by_cases hωu : ω ∈ u <;> by_cases hωv : ω ∈ v <;> simp [f, hωu, hωv]
  calc
    μ[(u ∩ v).indicator (fun _ => (1 : ℝ)) | ℱ t] =ᵐ[μ]
        μ[u.indicator f | ℱ t] := by rw [hinter]
    _ =ᵐ[μ] u.indicator μ[f | ℱ t] := condExp_indicator hf hu_filtration
    _ =ᵐ[μ] u.indicator μ[f | stateMeasurableSpace (X t)] :=
      by
        filter_upwards [hv_markov] with ω hω
        by_cases hωu : ω ∈ u
        · rw [Set.indicator_of_mem hωu, Set.indicator_of_mem hωu]
          simpa only [f] using hω
        · simp [hωu]
    _ =ᵐ[μ] μ[u.indicator f | stateMeasurableSpace (X t)] :=
      (condExp_indicator hf hu).symm
    _ =ᵐ[μ] μ[(u ∩ v).indicator (fun _ => (1 : ℝ)) |
        stateMeasurableSpace (X t)] := by rw [hinter]

/-- Finite-dimensional future cylinder events satisfy the Markov conditional-expectation
identity. The list is chronological; this makes the tower-property induction explicit. -/
theorem condExp_markovCylinderEvent [IsProbabilityMeasure μ]
    (hX : HasMarkovProperty X ℱ μ) {r : T} (l : List (T × Set E))
    (hl_meas : ∀ p ∈ l, MeasurableSet p.2)
    (hl_future : ∀ p ∈ l, r ≤ p.1)
    (hl_order : l.Pairwise fun p q => p.1 ≤ q.1) :
    μ[(markovCylinderEvent X l).indicator (fun _ => (1 : ℝ)) | ℱ r] =ᵐ[μ]
      μ[(markovCylinderEvent X l).indicator (fun _ => (1 : ℝ)) |
        stateMeasurableSpace (X r)] := by
  induction l generalizing r with
  | nil =>
      have hstate_r : stateMeasurableSpace (X r) ≤ ‹MeasurableSpace Ω› :=
        measurable_iff_comap_le.mp (hX.measurable_state r)
      rw [markovCylinderEvent_nil]
      simp only [Set.indicator_univ]
      exact Filter.Eventually.of_forall fun ω => by
        rw [condExp_const (ℱ.le r) (1 : ℝ), condExp_const hstate_r (1 : ℝ)]
  | cons p l ih =>
      rcases p with ⟨s, A⟩
      have hA : MeasurableSet A := hl_meas (s, A) (by simp)
      have hrs : r ≤ s := hl_future (s, A) (by simp)
      have hl_order' := (List.pairwise_cons.mp hl_order).2
      have hs_tail : ∀ q ∈ l, s ≤ q.1 := (List.pairwise_cons.mp hl_order).1
      have hl_meas' : ∀ q ∈ l, MeasurableSet q.2 := by
        intro q hq
        exact hl_meas q (by simp [hq])
      have htail := ih hl_meas' hs_tail hl_order'
      have htail_meas : MeasurableSet (markovCylinderEvent X l) :=
        measurableSet_markovCylinderEvent X l
          (fun p _ => hX.measurable_state p.1) hl_meas'
      have hstate_event :
          MeasurableSet[stateMeasurableSpace (X s)] (X s ⁻¹' A) :=
        (measurable_iff_comap_le.mpr le_rfl) hA
      have hat_s := hX.condExp_inter_stateEvent s hstate_event htail_meas htail
      exact hX.condExp_event_of_later hrs hat_s

end HasMarkovProperty

section LinearTime

variable {S Ω' E' : Type*} [LinearOrder S] [MeasurableSpace Ω'] [MeasurableSpace E']
  {X' : S → Ω' → E'} {ℱ' : Filtration S ‹MeasurableSpace Ω'›} {μ' : Measure Ω'}

namespace HasMarkovProperty

/-- The Markov identity for an arbitrary finite future cylinder. Internally the constraints are
sorted chronologically before applying the tower-property induction. -/
theorem condExp_futureCylinder [IsProbabilityMeasure μ']
    (hX : HasMarkovProperty X' ℱ' μ') {r : S} (l : List (S × Set E'))
    (hl_meas : ∀ p ∈ l, MeasurableSet p.2)
    (hl_future : ∀ p ∈ l, r ≤ p.1) :
    μ'[(markovCylinderEvent X' l).indicator (fun _ => (1 : ℝ)) | ℱ' r] =ᵐ[μ']
      μ'[(markovCylinderEvent X' l).indicator (fun _ => (1 : ℝ)) |
        stateMeasurableSpace (X' r)] := by
  let cmp : (S × Set E') → (S × Set E') → Bool := fun p q => decide (p.1 ≤ q.1)
  let sorted := l.mergeSort cmp
  have hsorted : sorted.Pairwise fun p q => p.1 ≤ q.1 := by
    have h := List.pairwise_mergeSort (l := l) (le := cmp)
      (fun a b c hab hbc => by
        simp only [cmp, decide_eq_true_eq] at hab hbc ⊢
        exact hab.trans hbc)
      (fun a b => by
        simp only [cmp, Bool.or_eq_true, decide_eq_true_eq]
        exact le_total a.1 b.1)
    simpa only [cmp, decide_eq_true_eq] using h
  have hsorted_meas : ∀ p ∈ sorted, MeasurableSet p.2 := by
    intro p hp
    exact hl_meas p (List.mem_mergeSort.mp hp)
  have hsorted_future : ∀ p ∈ sorted, r ≤ p.1 := by
    intro p hp
    exact hl_future p (List.mem_mergeSort.mp hp)
  have hresult := hX.condExp_markovCylinderEvent sorted hsorted_meas hsorted_future hsorted
  have hevent : markovCylinderEvent X' sorted = markovCylinderEvent X' l :=
    markovCylinderEvent_eq_of_perm X' (List.mergeSort_perm l cmp)
  simpa only [hevent] using hresult

/-- Past information and finite future cylinders are conditionally independent given the current
state. This is the load-bearing π-system statement for the full characterization. -/
theorem condIndepSets_past_futureCylinders [StandardBorelSpace Ω'] [IsProbabilityMeasure μ']
    (hX : HasMarkovProperty X' ℱ' μ') (r : S) :
    CondIndepSets (stateMeasurableSpace (X' r))
      (measurable_iff_comap_le.mp (hX.measurable_state r))
      {u : Set Ω' | MeasurableSet[ℱ' r] u} (futureCylinderEvents X' r) μ' := by
  have hstate : stateMeasurableSpace (X' r) ≤ ‹MeasurableSpace Ω'› :=
    measurable_iff_comap_le.mp (hX.measurable_state r)
  have hfuture : futureMeasurableSpace X' r ≤ ‹MeasurableSpace Ω'› :=
    futureMeasurableSpace_le X' r _ fun s _ => hX.measurable_state s
  refine (condIndepSets_iff
    (m' := stateMeasurableSpace (X' r)) (hm' := hstate)
    {u : Set Ω' | MeasurableSet[ℱ' r] u} (futureCylinderEvents X' r) ?_ ?_ μ').2 ?_
  · intro A hA
    exact (ℱ'.le r) A hA
  · rintro B ⟨l, hlm, hlf, rfl⟩
    exact measurableSet_markovCylinderEvent X' l
      (fun p _ => hX.measurable_state p.1) hlm
  · intro A B hA hB
    rcases hB with ⟨l, hlm, hlf, rfl⟩
    let B : Set Ω' := markovCylinderEvent X' l
    let fA : Ω' → ℝ := A.indicator fun _ => 1
    let fB : Ω' → ℝ := B.indicator fun _ => 1
    let g : Ω' → ℝ := μ'[fB | stateMeasurableSpace (X' r)]
    have hA_ambient : MeasurableSet A := (ℱ'.le r) A hA
    have hB_ambient : MeasurableSet B :=
      measurableSet_markovCylinderEvent X' l
        (fun p _ => hX.measurable_state p.1) hlm
    have hfA : Integrable fA μ' := (integrable_const (1 : ℝ)).indicator hA_ambient
    have hfB : Integrable fB μ' := (integrable_const (1 : ℝ)).indicator hB_ambient
    have hmul : fA * fB = (A ∩ B).indicator (fun _ => (1 : ℝ)) := by
      funext ω
      by_cases hωA : ω ∈ A <;> by_cases hωB : ω ∈ B <;>
        simp [fA, fB, hωA, hωB]
    have hprod : Integrable (fA * fB) μ' := by
      rw [hmul]
      exact (integrable_const (1 : ℝ)).indicator (hA_ambient.inter hB_ambient)
    have hmarkov : μ'[fB | ℱ' r] =ᵐ[μ'] g := by
      exact hX.condExp_futureCylinder l hlm hlf
    have hstate_F : stateMeasurableSpace (X' r) ≤ ℱ' r :=
      measurable_iff_comap_le.mp (hX.adapted r)
    have htower := condExp_condExp_of_le (f := fA * fB) hstate_F (ℱ'.le r) (μ := μ')
    have hpull_past : μ'[fA * fB | ℱ' r] =ᵐ[μ'] fA * μ'[fB | ℱ' r] :=
      condExp_mul_of_aestronglyMeasurable_left
        ((measurable_const.indicator hA).stronglyMeasurable.aestronglyMeasurable) hprod hfB
    have hAg : fA * g = A.indicator g := by
      funext ω
      by_cases hωA : ω ∈ A <;> simp [fA, hωA]
    have hprod_state : Integrable (fA * g) μ' := by
      rw [hAg]
      exact integrable_condExp.indicator hA_ambient
    have hpull_state :
        μ'[fA * g | stateMeasurableSpace (X' r)] =ᵐ[μ']
          μ'[fA | stateMeasurableSpace (X' r)] * g :=
      condExp_mul_of_aestronglyMeasurable_right
        stronglyMeasurable_condExp.aestronglyMeasurable hprod_state hfA
    calc
      μ'⟦A ∩ B | stateMeasurableSpace (X' r)⟧ =ᵐ[μ']
          μ'[fA * fB | stateMeasurableSpace (X' r)] := by rw [hmul]
      _ =ᵐ[μ'] μ'[μ'[fA * fB | ℱ' r] | stateMeasurableSpace (X' r)] := htower.symm
      _ =ᵐ[μ'] μ'[fA * μ'[fB | ℱ' r] | stateMeasurableSpace (X' r)] :=
        condExp_congr_ae hpull_past
      _ =ᵐ[μ'] μ'[fA * g | stateMeasurableSpace (X' r)] :=
        condExp_congr_ae (Filter.EventuallyEq.rfl.mul hmarkov)
      _ =ᵐ[μ'] μ'[fA | stateMeasurableSpace (X' r)] * g := hpull_state
      _ =ᵐ[μ'] μ'⟦A | stateMeasurableSpace (X' r)⟧ *
          μ'⟦B | stateMeasurableSpace (X' r)⟧ := Filter.EventuallyEq.rfl

/-- Klenke's conditional-independence characterization: at a deterministic time, the whole past
and the whole future are conditionally independent given the current state. -/
theorem condIndep_past_future [StandardBorelSpace Ω'] [IsProbabilityMeasure μ']
    (hX : HasMarkovProperty X' ℱ' μ') (r : S) :
    CondIndep (stateMeasurableSpace (X' r)) (ℱ' r) (futureMeasurableSpace X' r)
      (measurable_iff_comap_le.mp (hX.measurable_state r)) μ' := by
  have hF : ℱ' r ≤ ‹MeasurableSpace Ω'› := ℱ'.le r
  have hfuture : futureMeasurableSpace X' r ≤ ‹MeasurableSpace Ω'› :=
    futureMeasurableSpace_le X' r _ fun s _ => hX.measurable_state s
  refine CondIndepSets.condIndep hF hfuture
    (p1 := {u : Set Ω' | MeasurableSet[ℱ' r] u})
    (p2 := futureCylinderEvents X' r)
    (@MeasurableSpace.isPiSystem_measurableSet Ω' (ℱ' r))
    (isPiSystem_futureCylinderEvents X' r)
    (@MeasurableSpace.generateFrom_measurableSet Ω' (ℱ' r)).symm
    (generateFrom_futureCylinderEvents_eq X' r).symm
    (hX.condIndepSets_past_futureCylinders r)

end HasMarkovProperty

end LinearTime

/-- The real probability assigned by a kernel to a measurable event.  The conversion is safe for
Markov kernels because their values are finite. -/
def transitionProbability (κ : Kernel E E) (x : E) (A : Set E) : ℝ :=
  (κ x A).toReal

/-- A process has a selected forward transition representation when its event conditional
expectations agree with evaluation of that transition system. -/
structure HasTransitionSystem
    (X : T → Ω → E) (ℱ : Filtration T ‹MeasurableSpace Ω›) (μ : Measure Ω)
    (K : TransitionSystem T E) : Prop where
  adapted : Adapted ℱ X
  system : IsMarkovTransitionSystem K
  condExp_event : ∀ {r s : T} (hrs : r ≤ s) {A : Set E}, MeasurableSet A →
    μ[eventIndicator (X s) A | ℱ r] =ᵐ[μ]
      fun ω => transitionProbability (K r s hrs) (X r ω) A

/-- Homogeneous discrete transition representation, expressed through the lawful natural-time
transition system associated with a semigroup. -/
def HasTransitionSemigroup
    (X : ℕ → Ω → E) (ℱ : Filtration ℕ ‹MeasurableSpace Ω›) (μ : Measure Ω)
    (κ : ℕ → Kernel E E) : Prop :=
  HasTransitionSystem X ℱ μ (natTransitionSystem κ)

/-- The process observed a fixed number of steps after a possibly infinite stopping time. On the
null infinite-time set the canonical `WithTop.untopA` fallback is immaterial; strong-Markov
theorems below require almost-sure finiteness. -/
noncomputable def processAfterStopping (X : ℕ → Ω → E) (τ : Ω → WithTop ℕ)
    (n : ℕ) : Ω → E :=
  fun ω => X ((τ ω).untopA + n) ω

namespace HasTransitionSystem

variable {X : T → Ω → E} {ℱ : Filtration T ‹MeasurableSpace Ω›} {μ : Measure Ω}
  {K : TransitionSystem T E}

/-- Evaluation of a represented transition probability is measurable with respect to the current
state sigma-field. -/
theorem measurable_transitionProbability
    (_hX : HasTransitionSystem X ℱ μ K) {r s : T} (hrs : r ≤ s)
    {A : Set E} (hA : MeasurableSet A) :
    @Measurable Ω ℝ (stateMeasurableSpace (X r)) inferInstance
      (fun ω => transitionProbability (K r s hrs) (X r ω) A) := by
  exact ((K r s hrs).measurable_coe hA).ennreal_toReal.comp
    (measurable_iff_comap_le.mpr le_rfl)

set_option linter.style.haveILetI false in
/-- Transition probabilities are integrable under a finite law. -/
theorem integrable_transitionProbability [IsFiniteMeasure μ]
    (hX : HasTransitionSystem X ℱ μ K) {r s : T} (hrs : r ≤ s)
    {A : Set E} (hA : MeasurableSet A) :
    Integrable (fun ω => transitionProbability (K r s hrs) (X r ω) A) μ := by
  have hmeas := hX.measurable_transitionProbability hrs hA
  refine Integrable.mono' (integrable_const (1 : ℝ))
    (hmeas.mono (measurable_iff_comap_le.mp hX.adapted.measurable) le_rfl
      |>.stronglyMeasurable.aestronglyMeasurable) ?_
  filter_upwards [] with ω
  rw [transitionProbability, Real.norm_eq_abs, abs_of_nonneg ENNReal.toReal_nonneg]
  apply ENNReal.toReal_mono ENNReal.one_ne_top
  letI : IsMarkovKernel (K r s hrs) := hX.system.isMarkovKernel r s hrs
  calc
    (K r s hrs) (X r ω) A ≤ (K r s hrs) (X r ω) Set.univ :=
      measure_mono (Set.subset_univ A)
    _ = 1 := measure_univ

/-- A selected transition system implies the kernel-free Markov property. -/
theorem hasMarkovProperty [IsProbabilityMeasure μ]
    (hX : HasTransitionSystem X ℱ μ K) : HasMarkovProperty X ℱ μ where
  adapted := hX.adapted
  condExp_event := by
    intro r s hrs A hA
    have hmeas_state := hX.measurable_transitionProbability hrs hA
    have hint := hX.integrable_transitionProbability hrs hA
    have hstate_filtration : stateMeasurableSpace (X r) ≤ ℱ r :=
      measurable_iff_comap_le.mp (hX.adapted r)
    have hcond :
        μ[(fun ω => transitionProbability (K r s hrs) (X r ω) A) |
            stateMeasurableSpace (X r)] =
          fun ω => transitionProbability (K r s hrs) (X r ω) A :=
      condExp_of_stronglyMeasurable
        (measurable_iff_comap_le.mp hX.adapted.measurable)
        hmeas_state.stronglyMeasurable hint
    have hrepresentation := hX.condExp_event hrs hA
    have hcond_congr := condExp_congr_ae (m := stateMeasurableSpace (X r)) hrepresentation
    have htower := condExp_condExp_of_le (f := eventIndicator (X s) A)
      hstate_filtration (ℱ.le r) (μ := μ)
    have hrhs_cond :
        (fun ω => transitionProbability (K r s hrs) (X r ω) A) =ᵐ[μ]
          μ[(fun ω => transitionProbability (K r s hrs) (X r ω) A) |
            stateMeasurableSpace (X r)] :=
      Filter.Eventually.of_forall fun ω => (congrFun hcond ω).symm
    exact hrepresentation.trans (hrhs_cond.trans (hcond_congr.symm.trans htower))

end HasTransitionSystem

section DiscreteStrongMarkov

variable {Ωₙ Eₙ : Type*} [MeasurableSpace Ωₙ] [MeasurableSpace Eₙ]
  {Xₙ : ℕ → Ωₙ → Eₙ} {ℱₙ : Filtration ℕ ‹MeasurableSpace Ωₙ›} {μₙ : Measure Ωₙ}
  {κₙ : ℕ → Kernel Eₙ Eₙ}

/-- Countable-time strong Markov property for a homogeneous transition representation. The
stopping time may be unbounded and may equal infinity on a null set; no finite fallback is used in
the mathematical statement. -/
theorem strongMarkov_event_countable [IsProbabilityMeasure μₙ]
    (hX : HasTransitionSemigroup Xₙ ℱₙ μₙ κₙ)
    {τ : Ωₙ → WithTop ℕ} (hτ : IsStoppingTime ℱₙ τ)
    (hτ_finite : ∀ᵐ ω ∂μₙ, τ ω ≠ (⊤ : WithTop ℕ))
    (n : ℕ) {A : Set Eₙ} (hA : MeasurableSet A) :
    μₙ[eventIndicator (processAfterStopping Xₙ τ n) A | hτ.measurableSpace] =ᵐ[μₙ]
      fun ω => transitionProbability (κₙ n) (stoppedValue Xₙ τ ω) A := by
  let futureEvent : Ωₙ → ℝ := eventIndicator (processAfterStopping Xₙ τ n) A
  let stoppedTransition : Ωₙ → ℝ :=
    fun ω => transitionProbability (κₙ n) (stoppedValue Xₙ τ ω) A
  have hslice_meas (k : ℕ) : MeasurableSet {ω : Ωₙ | τ ω = k} :=
    (ℱₙ.le k) _ (hτ.measurableSet_eq_of_countable k)
  have htop_eq : {ω : Ωₙ | τ ω = (⊤ : WithTop ℕ)} =
      (⋃ k : ℕ, {ω | τ ω = k})ᶜ := by
    ext ω
    cases hω : τ ω with
    | top => simp [hω]
    | coe k => simp [hω]
  have htop_meas : MeasurableSet {ω : Ωₙ | τ ω = (⊤ : WithTop ℕ)} := by
    rw [htop_eq]
    exact (MeasurableSet.iUnion hslice_meas).compl
  have hfuture_set : MeasurableSet (processAfterStopping Xₙ τ n ⁻¹' A) := by
    have heq : processAfterStopping Xₙ τ n ⁻¹' A =
        (⋃ k : ℕ, {ω | τ ω = k} ∩ Xₙ (k + n) ⁻¹' A) ∪
          ({ω | τ ω = (⊤ : WithTop ℕ)} ∩
            Xₙ ((⊤ : WithTop ℕ).untopA + n) ⁻¹' A) := by
      ext ω
      cases hω : τ ω with
      | top => simp [processAfterStopping, hω]
      | coe k =>
          simp only [Set.mem_preimage, Set.mem_union, Set.mem_iUnion, Set.mem_inter_iff,
            processAfterStopping, hω]
          rw [WithTop.untopA_eq_untop WithTop.coe_ne_top, WithTop.untop_coe]
          simp [hω]
    rw [heq]
    exact (MeasurableSet.iUnion fun k =>
      (hslice_meas k).inter ((ℱₙ.le (k + n)) _ ((hX.adapted (k + n)) hA))).union
      (htop_meas.inter ((ℱₙ.le ((⊤ : WithTop ℕ).untopA + n)) _
        ((hX.adapted ((⊤ : WithTop ℕ).untopA + n)) hA)))
  have hfuture_int : Integrable futureEvent μₙ :=
    (integrable_const (1 : ℝ)).indicator hfuture_set
  have hslice (k : ℕ) :
      μₙ[futureEvent | hτ.measurableSpace] =ᵐ[μₙ.restrict {ω | τ ω = k}]
        stoppedTransition := by
    let deterministicEvent : Ωₙ → ℝ := eventIndicator (Xₙ (k + n)) A
    let deterministicTransition : Ωₙ → ℝ :=
      fun ω => transitionProbability (κₙ n) (Xₙ k ω) A
    have hdet_set : MeasurableSet (Xₙ (k + n) ⁻¹' A) :=
      (ℱₙ.le (k + n)) _ ((hX.adapted (k + n)) hA)
    have hdet_int : Integrable deterministicEvent μₙ :=
      (integrable_const (1 : ℝ)).indicator hdet_set
    have hfun_slice : futureEvent =ᵐ[μₙ.restrict {ω | τ ω = k}] deterministicEvent := by
      apply (ae_restrict_iff' (hslice_meas k)).2
      exact Filter.Eventually.of_forall fun ω hω => by
        have hk : ((k : WithTop ℕ).untopA) = k := by
          exact (WithTop.untopA_eq_untop (a := (k : WithTop ℕ))
            WithTop.coe_ne_top).trans (WithTop.untop_coe k)
        have hindex : (τ ω).untopA + n = k + n := by
          rw [hω, hk]
        change eventIndicator (Xₙ ((τ ω).untopA + n)) A ω =
          eventIndicator (Xₙ (k + n)) A ω
        rw [hindex]
    have hcond_local :
        μₙ[futureEvent | ℱₙ k] =ᵐ[μₙ.restrict {ω | τ ω = k}]
          μₙ[deterministicEvent | ℱₙ k] := by
      calc
        μₙ[futureEvent | ℱₙ k] =ᵐ[μₙ.restrict {ω | τ ω = k}]
            (μₙ.restrict {ω | τ ω = k})[futureEvent | ℱₙ k] :=
          (condExp_restrict_ae_eq_restrict (ℱₙ.le k) (hτ.measurableSet_eq k)
            hfuture_int).symm
        _ =ᵐ[μₙ.restrict {ω | τ ω = k}]
            (μₙ.restrict {ω | τ ω = k})[deterministicEvent | ℱₙ k] :=
          condExp_congr_ae hfun_slice
        _ =ᵐ[μₙ.restrict {ω | τ ω = k}]
            μₙ[deterministicEvent | ℱₙ k] :=
          condExp_restrict_ae_eq_restrict (ℱₙ.le k) (hτ.measurableSet_eq k) hdet_int
    have hkn : k ≤ k + n := Nat.le_add_right k n
    have hdeterministic :
        μₙ[deterministicEvent | ℱₙ k] =ᵐ[μₙ] deterministicTransition := by
      simpa [HasTransitionSemigroup, natTransitionSystem, deterministicEvent,
        deterministicTransition] using hX.condExp_event hkn hA
    have hstop :
        μₙ[futureEvent | hτ.measurableSpace] =ᵐ[μₙ.restrict {ω | τ ω = k}]
          μₙ[futureEvent | ℱₙ k] :=
      condExp_stopping_time_ae_eq_restrict_eq_of_countable
        (μ := μₙ) (ℱ := ℱₙ) (τ := τ) (f := futureEvent) hτ k
    have hrhs_slice : deterministicTransition =ᵐ[μₙ.restrict {ω | τ ω = k}]
        stoppedTransition := by
      apply (ae_restrict_iff' (hslice_meas k)).2
      exact Filter.Eventually.of_forall fun ω hω => by
        have hk : ((k : WithTop ℕ).untopA) = k := by
          exact (WithTop.untopA_eq_untop (a := (k : WithTop ℕ))
            WithTop.coe_ne_top).trans (WithTop.untop_coe k)
        have hvalue : stoppedValue Xₙ τ ω = Xₙ k ω := by
          change Xₙ ((τ ω).untopA) ω = Xₙ k ω
          rw [hω, hk]
        simp only [deterministicTransition, stoppedTransition, hvalue]
    exact hstop.trans (hcond_local.trans (hdeterministic.restrict.trans hrhs_slice))
  have hslice_ae : ∀ᵐ ω ∂μₙ, ∀ k : ℕ, τ ω = k →
      μₙ[futureEvent | hτ.measurableSpace] ω = stoppedTransition ω := by
    rw [ae_all_iff]
    intro k
    exact (ae_restrict_iff' (hslice_meas k)).mp (hslice k)
  filter_upwards [hslice_ae, hτ_finite] with ω hω hωfinite
  cases hτω : τ ω with
  | top => exact (hωfinite hτω).elim
  | coe k => exact hω k hτω

end DiscreteStrongMarkov

end ProbabilityTheory
