/-
Copyright (c) 2026 StochLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: StochLean contributors
-/
module

public import StochLean.Probability.Process.Poisson.Constructions
public import StochLean.Probability.Process.Poisson.FiniteIncrementLaw

/-!
# Arrival-time counting processes

This module lifts the deterministic nonexplosive arrival/count inverse to random arrival
sequences.  All path properties hold pointwise, hence on one common probability-one event.  The
remaining probabilistic input is stated as the arbitrary finite-partition law from
`HasFinitePoissonIncrementLaws`, never as pairwise independence alone.
-/

@[expose] public section

open MeasureTheory

namespace ProbabilityTheory.PoissonProcess

noncomputable section

variable {Ω : Type*} {mΩ : MeasurableSpace Ω} {P : Measure Ω}

/-- The random counting process generated by a random nonexplosive sequence of strictly positive
interarrival times. -/
def arrivalCountProcess (A : Ω → DivergentArrivalSequence) : NNReal → Ω → ℕ :=
  fun t ω ↦ (A ω).count t

@[simp]
theorem DivergentArrivalSequence.count_zero (a : DivergentArrivalSequence) : a.count 0 = 0 := by
  apply Nat.eq_zero_of_le_zero
  rw [a.count_le_iff 0 0]
  simpa only [eventTime, arrivalTime, Finset.sum_range_succ, Finset.sum_range_zero,
    zero_add] using a.positive 0

@[simp]
theorem arrivalCountProcess_zero (A : Ω → DivergentArrivalSequence) :
    arrivalCountProcess A 0 = fun _ ↦ 0 := by
  funext ω
  exact (A ω).count_zero

/-- Every random divergent-arrival count has monotone paths on the whole sample space. -/
theorem hasMonotonePaths_arrivalCountProcess (A : Ω → DivergentArrivalSequence) :
    HasMonotonePaths (arrivalCountProcess A) P :=
  ae_of_all _ fun ω ↦ (A ω).monotone_count

/-- Every random divergent-arrival count has right-continuous paths on the whole sample space. -/
theorem hasRightContinuousPaths_arrivalCountProcess (A : Ω → DivergentArrivalSequence) :
    HasRightContinuousPaths (arrivalCountProcess A) P :=
  ae_of_all _ fun ω ↦ (A ω).isRightContinuousPath_count

/-- Arrival-time construction principle.  Once the exponential waiting-time calculation supplies
the joint law for every finite ordered partition, the deterministic inverse automatically
provides the corrected common-event path axioms of a Poisson process. -/
theorem isPoissonProcess_arrivalCountProcess [IsProbabilityMeasure P]
    (A : Ω → DivergentArrivalSequence) (rate : NNReal)
    (hmeas : ∀ t, AEMeasurable (arrivalCountProcess A t) P)
    (hLaw : HasFinitePoissonIncrementLaws (arrivalCountProcess A) rate P) :
    IsPoissonProcess (arrivalCountProcess A) rate P :=
  hLaw.isPoissonProcess hmeas
    (Filter.Eventually.of_forall fun ω ↦ by simp)
    (hasMonotonePaths_arrivalCountProcess A)
    (hasRightContinuousPaths_arrivalCountProcess A)

end

end ProbabilityTheory.PoissonProcess
