/-
Copyright (c) 2026 StochLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: StochLean contributors
-/
module

public import StochLean.Probability.Process.Poisson.Basic
public import Mathlib.Data.Fintype.Card
public import Mathlib.Data.Nat.Find

/-!
# Deterministic cores of Poisson-process constructions

This file isolates the pathwise maps used by the uniform-point and exponential-arrival
constructions. Their probabilistic laws can then be proved without changing representations.
-/

@[expose] public section

open Filter Finset
open scoped Topology

namespace ProbabilityTheory.PoissonProcess

noncomputable section

/-- The counting path generated by finitely many points in the unit interval. -/
def uniformPointCount {n : ℕ} (u : Fin n → unitInterval) (t : unitInterval) : ℕ :=
  (univ.filter fun i ↦ u i ≤ t).card

/-- A uniform-point counting path is monotone. -/
lemma monotone_uniformPointCount {n : ℕ} (u : Fin n → unitInterval) :
    Monotone (uniformPointCount u) := by
  intro s t hst
  apply card_le_card
  intro i hi
  simp only [mem_filter, mem_univ, true_and] at hi ⊢
  exact hi.trans hst

@[simp]
lemma uniformPointCount_one {n : ℕ} (u : Fin n → unitInterval) :
    uniformPointCount u 1 = n := by
  rw [uniformPointCount, filter_eq_self.mpr]
  · exact card_fin n
  · intro i _
    exact (u i).property.2

lemma uniformPointCount_zero_of_pos {n : ℕ} (u : Fin n → unitInterval)
    (hu : ∀ i, 0 < u i) : uniformPointCount u 0 = 0 := by
  have hf : (univ.filter fun i ↦ u i ≤ (0 : unitInterval)) = ∅ := by
    apply filter_eq_empty_iff.mpr
    intro i _
    exact not_le.mpr (hu i)
  simp only [uniformPointCount, hf, card_empty]

/-- Partial arrival times associated with a sequence of nonnegative interarrival durations. -/
def arrivalTime (interarrival : ℕ → NNReal) (n : ℕ) : NNReal :=
  ∑ i ∈ range n, interarrival i

/-- Interarrival data whose partial sums diverge. The positivity field matches exponential
interarrivals; the explicit divergence field prevents a totalized count for explosive paths. -/
structure DivergentArrivalSequence where
  interarrival : ℕ → NNReal
  positive : ∀ n, 0 < interarrival n
  tendsto_arrivalTime : Tendsto (arrivalTime interarrival) atTop atTop

namespace DivergentArrivalSequence

/-- Time of the event with zero-based index `n`. -/
def eventTime (a : DivergentArrivalSequence) (n : ℕ) : NNReal :=
  arrivalTime a.interarrival (n + 1)

/-- Strictly positive interarrivals give strictly increasing event times. -/
lemma strictMono_eventTime (a : DivergentArrivalSequence) : StrictMono a.eventTime := by
  refine strictMono_nat_of_lt_succ fun n ↦ ?_
  simp only [eventTime, arrivalTime, Nat.reduceAdd, sum_range_succ, Nat.add_assoc]
  exact lt_add_of_pos_right _ (a.positive (n + 1))

lemma exists_eventTime_gt (a : DivergentArrivalSequence) (t : NNReal) :
    ∃ n, t < a.eventTime n := by
  have ht : Tendsto (a.eventTime) atTop atTop :=
    a.tendsto_arrivalTime.comp (tendsto_add_atTop_nat 1)
  obtain ⟨n, hn⟩ := ((tendsto_atTop.1 ht) (t + 1)).exists
  exact ⟨n, (lt_add_of_pos_right t zero_lt_one).trans_le hn⟩

/-- The number of arrivals at or before time `t`, defined as the first event strictly after `t`.
Existence follows from divergence, rather than from a fallback value for explosive paths. -/
def count (a : DivergentArrivalSequence) (t : NNReal) : ℕ :=
  Nat.find (a.exists_eventTime_gt t)

lemma lt_eventTime_count (a : DivergentArrivalSequence) (t : NNReal) :
    t < a.eventTime (a.count t) :=
  Nat.find_spec (a.exists_eventTime_gt t)

lemma eventTime_le_of_lt_count (a : DivergentArrivalSequence) (t : NNReal) {n : ℕ}
    (hn : n < a.count t) : a.eventTime n ≤ t := by
  apply le_of_not_gt
  intro hnt
  exact (not_le_of_gt hn) (Nat.find_min' (a.exists_eventTime_gt t) hnt)

/-- The count is at most `n` exactly before the event with zero-based index `n`. -/
lemma count_le_iff (a : DivergentArrivalSequence) (t : NNReal) (n : ℕ) :
    a.count t ≤ n ↔ t < a.eventTime n := by
  constructor
  · intro h
    exact (a.lt_eventTime_count t).trans_le (a.strictMono_eventTime.monotone h)
  · intro h
    exact Nat.find_min' (a.exists_eventTime_gt t) h

/-- The event with index `n` has occurred exactly when the count exceeds `n`. -/
lemma lt_count_iff (a : DivergentArrivalSequence) (t : NNReal) (n : ℕ) :
    n < a.count t ↔ a.eventTime n ≤ t := by
  constructor
  · exact a.eventTime_le_of_lt_count t
  · intro h
    by_contra hn
    have hcount : a.count t ≤ n := Nat.le_of_not_gt hn
    have hstrict : t < a.eventTime n :=
      (a.lt_eventTime_count t).trans_le (a.strictMono_eventTime.monotone hcount)
    exact (not_lt_of_ge h) hstrict

/-- At the time of the event with zero-based index `n`, exactly `n + 1` events have occurred. -/
@[simp]
lemma count_eventTime (a : DivergentArrivalSequence) (n : ℕ) :
    a.count (a.eventTime n) = n + 1 := by
  apply Nat.le_antisymm
  · exact (a.count_le_iff (a.eventTime n) (n + 1)).mpr
      (a.strictMono_eventTime (Nat.lt_succ_self n))
  · exact Nat.succ_le_iff.mpr ((a.lt_count_iff (a.eventTime n) n).mpr le_rfl)

/-- Arrival counts are monotone in time. -/
lemma monotone_count (a : DivergentArrivalSequence) : Monotone a.count := by
  intro s t hst
  apply Nat.find_min' (a.exists_eventTime_gt s)
  exact hst.trans_lt (a.lt_eventTime_count t)

/-- A nonexplosive positive-interarrival counting path is right-continuous. -/
theorem isRightContinuousPath_count (a : DivergentArrivalSequence) :
    IsRightContinuousPath a.count := by
  intro t
  have heq : a.count =ᶠ[𝓝[Set.Ici t] t] fun _ ↦ a.count t := by
    filter_upwards [eventually_nhdsWithin_of_eventually_nhds
      (Iio_mem_nhds (a.lt_eventTime_count t)), self_mem_nhdsWithin] with u hu htu
    apply le_antisymm
    · apply Nat.find_min' (a.exists_eventTime_gt u)
      exact hu
    · exact a.monotone_count htu
  exact continuousWithinAt_const.congr_of_eventuallyEq heq rfl

end DivergentArrivalSequence

end

end ProbabilityTheory.PoissonProcess
