/-
Copyright (c) 2026 StochLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: StochLean contributors
-/
module

public import StochLean.Probability.Process.Poisson.Basic
public import Mathlib.Data.Fintype.Card
public import Mathlib.Data.Nat.Find

/-!
# Deterministic cores of Poisson-process constructions

This file isolates the pathwise maps used by the uniform-point and exponential-arrival
constructions. Their probabilistic laws can then be proved without changing representations.
-/

@[expose] public section

open Filter Finset

namespace ProbabilityTheory.PoissonProcess

noncomputable section

/-- The counting path generated by finitely many points in the unit interval. -/
def uniformPointCount {n : ℕ} (u : Fin n → unitInterval) (t : unitInterval) : ℕ :=
  (univ.filter fun i ↦ u i ≤ t).card

/-- A uniform-point counting path is monotone. -/
lemma monotone_uniformPointCount {n : ℕ} (u : Fin n → unitInterval) :
    Monotone (uniformPointCount u) := by
  intro s t hst
  apply card_le_card
  intro i hi
  simp only [mem_filter, mem_univ, true_and] at hi ⊢
  exact hi.trans hst

@[simp]
lemma uniformPointCount_one {n : ℕ} (u : Fin n → unitInterval) :
    uniformPointCount u 1 = n := by
  rw [uniformPointCount, filter_eq_self.mpr]
  · exact card_fin n
  · intro i _
    exact (u i).property.2

lemma uniformPointCount_zero_of_pos {n : ℕ} (u : Fin n → unitInterval)
    (hu : ∀ i, 0 < u i) : uniformPointCount u 0 = 0 := by
  have hf : (univ.filter fun i ↦ u i ≤ (0 : unitInterval)) = ∅ := by
    apply filter_eq_empty_iff.mpr
    intro i _
    exact not_le.mpr (hu i)
  simp only [uniformPointCount, hf, card_empty]

/-- Partial arrival times associated with a sequence of nonnegative interarrival durations. -/
def arrivalTime (interarrival : ℕ → NNReal) (n : ℕ) : NNReal :=
  ∑ i ∈ range n, interarrival i

/-- Interarrival data whose partial sums diverge. The positivity field matches exponential
interarrivals; the explicit divergence field prevents a totalized count for explosive paths. -/
structure DivergentArrivalSequence where
  interarrival : ℕ → NNReal
  positive : ∀ n, 0 < interarrival n
  tendsto_arrivalTime : Tendsto (arrivalTime interarrival) atTop atTop

namespace DivergentArrivalSequence

/-- Time of the event with zero-based index `n`. -/
def eventTime (a : DivergentArrivalSequence) (n : ℕ) : NNReal :=
  arrivalTime a.interarrival (n + 1)

lemma exists_eventTime_gt (a : DivergentArrivalSequence) (t : NNReal) :
    ∃ n, t < a.eventTime n := by
  have ht : Tendsto (a.eventTime) atTop atTop :=
    a.tendsto_arrivalTime.comp (tendsto_add_atTop_nat 1)
  obtain ⟨n, hn⟩ := ((tendsto_atTop.1 ht) (t + 1)).exists
  exact ⟨n, (lt_add_of_pos_right t zero_lt_one).trans_le hn⟩

/-- The number of arrivals at or before time `t`, defined as the first event strictly after `t`.
Existence follows from divergence, rather than from a fallback value for explosive paths. -/
def count (a : DivergentArrivalSequence) (t : NNReal) : ℕ :=
  Nat.find (a.exists_eventTime_gt t)

lemma lt_eventTime_count (a : DivergentArrivalSequence) (t : NNReal) :
    t < a.eventTime (a.count t) :=
  Nat.find_spec (a.exists_eventTime_gt t)

lemma eventTime_le_of_lt_count (a : DivergentArrivalSequence) (t : NNReal) {n : ℕ}
    (hn : n < a.count t) : a.eventTime n ≤ t := by
  apply le_of_not_gt
  intro hnt
  exact (not_le_of_gt hn) (Nat.find_min' (a.exists_eventTime_gt t) hnt)

/-- Arrival counts are monotone in time. -/
lemma monotone_count (a : DivergentArrivalSequence) : Monotone a.count := by
  intro s t hst
  apply Nat.find_min' (a.exists_eventTime_gt s)
  exact hst.trans_lt (a.lt_eventTime_count t)

end DivergentArrivalSequence

end

end ProbabilityTheory.PoissonProcess
