/-
Copyright (c) 2026 StochLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: StochLean contributors
-/
module

public import StochLean.Probability.Distributions.Poissonization
public import StochLean.Probability.Process.Poisson.Constructions
public import Mathlib.MeasureTheory.Constructions.UnitInterval

/-!
# The uniform-point construction on the unit interval

The construction is separated into two canonical law-level stages.  A measurable finite
categorization of one uniform point gives a `PMF`; a fixed number of independent points gives the
corresponding multinomial count law.  Mixing the number of points with a Poisson law then splits
the cell counts into independent Poisson coordinates.  Taking the cells to be successive
intervals is Klenke's uniform-point construction.
-/

@[expose] public section

open MeasureTheory
open scoped ENNReal unitInterval

namespace ProbabilityTheory

noncomputable section

variable {κ : Type*} [Fintype κ] [MeasurableSpace κ] [MeasurableSingletonClass κ]

namespace PMF

/-- The categorical law obtained by applying a finite measurable classifier to one uniform point
of the unit interval. -/
def uniformCategory (c : unitInterval → κ) (hc : Measurable c) : PMF κ := by
  let Q := (volume : Measure unitInterval).map c
  let _ : IsProbabilityMeasure Q :=
    Measure.isProbabilityMeasure_map hc.aemeasurable
  exact Q.toPMF

@[simp]
theorem uniformCategory_toMeasure (c : unitInterval → κ) (hc : Measurable c) :
    (uniformCategory c hc).toMeasure = (volume : Measure unitInterval).map c := by
  let Q := (volume : Measure unitInterval).map c
  let _ : IsProbabilityMeasure Q :=
    Measure.isProbabilityMeasure_map hc.aemeasurable
  change Q.toPMF.toMeasure = Q
  exact Measure.toPMF_toMeasure Q

/-- The count-vector law generated by a Poisson number of uniform points classified by `c`. -/
def poissonizedUniformCounts (r : NNReal) (c : unitInterval → κ) (hc : Measurable c) :
    PMF (κ → ℕ) :=
  poissonizedMultinomial r (uniformCategory c hc)

end PMF

namespace PoissonProcess

/-- The number of points assigned to each cell by a finite classifier. -/
def uniformCategoryCounts {n : ℕ} (c : unitInterval → κ) (u : Fin n → unitInterval) : κ → ℕ :=
  categoricalCounts fun i ↦ c (u i)

set_option linter.unusedFintypeInType false in
/-- The uniform cell-count map is measurable on every finite product sample space. -/
theorem measurable_uniformCategoryCounts {n : ℕ} (c : unitInterval → κ) (hc : Measurable c) :
    Measurable (uniformCategoryCounts (n := n) c) :=
  measurable_categoricalCounts.comp <|
    measurable_pi_lambda _ fun i ↦ hc.comp (measurable_pi_apply i)

/-- A fixed number of independent uniform points has the multinomial cell-count law. -/
theorem hasLaw_uniformCategoryCounts {n : ℕ} (c : unitInterval → κ) (hc : Measurable c) :
    HasLaw (uniformCategoryCounts (n := n) c)
      (PMF.multinomial (PMF.uniformCategory c hc) n).toMeasure
      (Measure.pi fun _ : Fin n ↦ (volume : Measure unitInterval)) := by
  have hEval : iIndepFun (fun i (u : Fin n → unitInterval) ↦ u i)
      (Measure.pi fun _ : Fin n ↦ (volume : Measure unitInterval)) :=
    iIndepFun_pi (X := fun _ ↦ id) (fun _ ↦ aemeasurable_id)
  have hLaw : ∀ i, HasLaw (fun u : Fin n → unitInterval ↦ u i)
      (volume : Measure unitInterval)
      (Measure.pi fun _ : Fin n ↦ (volume : Measure unitInterval)) :=
    fun i ↦ (measurePreserving_eval (fun _ : Fin n ↦ (volume : Measure unitInterval)) i).hasLaw
  have hcLaw : HasLaw c (PMF.uniformCategory c hc).toMeasure
      (volume : Measure unitInterval) := by
    refine ⟨hc.aemeasurable, ?_⟩
    exact (PMF.uniformCategory_toMeasure c hc).symm
  change HasLaw (fun u ↦ categoricalCounts fun i ↦ c (u i))
    (PMF.multinomial (PMF.uniformCategory c hc) n).toMeasure
    (Measure.pi fun _ : Fin n ↦ (volume : Measure unitInterval))
  exact hEval.hasLaw_multinomial_of_comp hLaw hc hcLaw

/-- Poissonization splits uniform finite-cell counts into independent Poisson counts. -/
theorem poissonizedUniformCounts_eq_independent (r : NNReal)
    (c : unitInterval → κ) (hc : Measurable c) :
    PMF.poissonizedUniformCounts r c hc =
      PMF.independentPoissonCounts r (PMF.uniformCategory c hc) :=
  by
    simpa only [PMF.poissonizedUniformCounts] using
      PMF.poissonizedMultinomial_eq_independentPoissonCounts r (PMF.uniformCategory c hc)

/-- Rate-identification form of the uniform-point splitting theorem.  For successive interval
cells, `q a` is their length, by `unitInterval.volume_Iic`/`unitInterval.volume_Ioc`. -/
theorem poissonizedUniformCounts_eq_independent_of_probabilities (r : NNReal)
    (c : unitInterval → κ) (hc : Measurable c) (q : κ → NNReal)
    (hq : ∀ a, (PMF.uniformCategory c hc a).toNNReal = q a) :
    PMF.poissonizedUniformCounts r c hc =
      (Measure.pi fun a ↦ poissonMeasure (r * q a)).toPMF := by
  rw [poissonizedUniformCounts_eq_independent]
  apply PMF.toMeasure_injective
  rw [PMF.independentPoissonCounts_toMeasure, Measure.toPMF_toMeasure]
  congr 2
  funext a
  rw [hq a]

/-- Successive interval cells have exactly their length as categorical mass.  The classifier is
kept as an argument so clients may choose any boundary convention; the displayed fibre condition
records Klenke's `(tᵢ,tᵢ₊₁]` convention exactly. -/
theorem uniformCategory_toNNReal_of_intervalFibers {n : ℕ}
    (t : Fin (n + 1) → unitInterval) (c : unitInterval → Fin n) (hc : Measurable c)
    (hfiber : ∀ i, c ⁻¹' ({i} : Set (Fin n)) = Set.Ioc (t i.castSucc) (t i.succ))
    (i : Fin n) :
    (PMF.uniformCategory c hc i).toNNReal =
      Real.toNNReal ((t i.succ : ℝ) - (t i.castSucc : ℝ)) := by
  apply NNReal.eq
  rw [ENNReal.coe_toNNReal_eq_toReal]
  rw [← (PMF.uniformCategory c hc).toMeasure_apply_singleton i (measurableSet_singleton i)]
  change (PMF.uniformCategory c hc).toMeasure.real {i} = _
  rw [PMF.uniformCategory_toMeasure, Measure.real,
    Measure.map_apply hc (measurableSet_singleton i),
    hfiber, unitInterval.volume_Ioc, ENNReal.toReal_ofReal']
  exact (Real.coe_toNNReal' _).symm

/-- Klenke 5.35, finite-partition law: Poissonizing independent uniform points makes the counts
in successive `(tᵢ,tᵢ₊₁]` cells independent Poisson variables with rate equal to cell length. -/
theorem poissonizedUniformIntervalCounts_eq_independent {n : ℕ} (r : NNReal)
    (t : Fin (n + 1) → unitInterval) (c : unitInterval → Fin n) (hc : Measurable c)
    (hfiber : ∀ i, c ⁻¹' ({i} : Set (Fin n)) = Set.Ioc (t i.castSucc) (t i.succ)) :
    PMF.poissonizedUniformCounts r c hc =
      (Measure.pi fun i : Fin n ↦
        poissonMeasure (r *
          Real.toNNReal ((t i.succ : ℝ) - (t i.castSucc : ℝ)))).toPMF :=
  poissonizedUniformCounts_eq_independent_of_probabilities r c hc _
    (uniformCategory_toNNReal_of_intervalFibers t c hc hfiber)

end PoissonProcess

end

end ProbabilityTheory
