/-
Copyright (c) 2026 StochLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: StochLean contributors
-/
module

public import StochLean.Probability.Exchangeability.SigmaFields
public import Mathlib.Probability.Martingale.Convergence
public import Mathlib.MeasureTheory.Function.ConvergenceInMeasure
public import Mathlib.Probability.Independence.ZeroOne

/-!
# Exchangeable and tail sigma-fields modulo a law

This file proves the probabilistic reverse inclusion missing from the raw sigma-field relation
`tailMeasurableSpace_le_exchangeableMeasurableSpace`.  The proof approximates an invariant-event
indicator by finite-coordinate conditional expectations, moves each approximation beyond an
arbitrary cutoff by a finite block permutation, and closes the tail subspaces in `L¹`.
-/

@[expose] public section

open scoped ENNReal
open MeasureTheory Filter

namespace ProbabilityTheory

variable {E : Type*} [MeasurableSpace E]

set_option linter.style.haveILetI false in
/-- Real-valued a.e. measurability descends through a decreasing countable family of
sigma-fields.  The `liminf` construction supplies one common measurable representative. -/
private theorem aestronglyMeasurable_iInf_antitone_real
    {Ω : Type*} {mΩ : MeasurableSpace Ω} {μ : @Measure Ω mΩ}
    {m : ℕ → MeasurableSpace Ω} (hanti : Antitone m) (_hle : ∀ n, m n ≤ mΩ)
    (f : Ω → ℝ) (hf : ∀ n, @AEStronglyMeasurable Ω ℝ _ (m n) mΩ f μ) :
    @AEStronglyMeasurable Ω ℝ _ (⨅ n, m n) mΩ f μ := by
  let g : ℕ → Ω → ℝ := fun n ↦ (hf n).mk f
  have hgmeas : ∀ n, @Measurable Ω ℝ (m n) _ (g n) :=
    fun n ↦ (hf n).stronglyMeasurable_mk.measurable
  have hgae : ∀ n, f =ᵐ[μ] g n := fun n ↦ (hf n).ae_eq_mk
  let h : Ω → ℝ := fun x ↦ Filter.liminf (fun n ↦ g n x) atTop
  have hmeasEach : ∀ n, @Measurable Ω ℝ (m n) _ h := by
    intro n
    have hshift : h = fun x ↦ Filter.liminf (fun k ↦ g (k + n) x) atTop := by
      funext x
      exact (Filter.liminf_nat_add (fun k ↦ g k x) n).symm
    rw [hshift]
    have hgshift : ∀ k, @Measurable Ω ℝ (m n) _ (g (k + n)) :=
      fun k ↦ (hgmeas (k + n)).mono (hanti (Nat.le_add_left n k)) le_rfl
    letI : MeasurableSpace Ω := m n
    exact Measurable.liminf hgshift
  have hmeas : @Measurable Ω ℝ (⨅ n, m n) _ h := by
    intro s hs
    rw [MeasurableSpace.measurableSet_iInf]
    exact fun n ↦ hmeasEach n hs
  have hae : f =ᵐ[μ] h := by
    have hall : ∀ᵐ x ∂μ, ∀ n, f x = g n x := ae_all_iff.mpr hgae
    filter_upwards [hall] with x hx
    simp [h, fun n ↦ (hx n).symm, Filter.liminf_const]
  have hstrong : @StronglyMeasurable Ω ℝ _ (⨅ n, m n) h := by
    letI : MeasurableSpace Ω := ⨅ n, m n
    exact hmeas.stronglyMeasurable
  exact ⟨h, hstrong, hae⟩

set_option linter.style.haveILetI false in
/-- A pointwise a.e. limit of real-valued functions measurable for a sub-sigma-field has an
a.e.-equal representative measurable for that sub-sigma-field. -/
private theorem aestronglyMeasurable_sub_of_tendsto_ae_real
    {Ω : Type*} {mΩ : MeasurableSpace Ω} {μ : @Measure Ω mΩ}
    {m : MeasurableSpace Ω} (_hm : m ≤ mΩ) {f : ℕ → Ω → ℝ} {g : Ω → ℝ}
    (hf : ∀ n, @Measurable Ω ℝ m _ (f n))
    (hlim : ∀ᵐ x ∂μ, Tendsto (fun n ↦ f n x) atTop (nhds (g x))) :
    @AEStronglyMeasurable Ω ℝ _ m mΩ g μ := by
  let h : Ω → ℝ := fun x ↦ Filter.limsup (fun n ↦ f n x) atTop
  have hmeas : @Measurable Ω ℝ m _ h := by
    letI : MeasurableSpace Ω := m
    exact Measurable.limsup hf
  have hae : h =ᵐ[μ] g := hlim.mono fun _ hx ↦ Filter.Tendsto.limsup_eq hx
  have hstrong : @StronglyMeasurable Ω ℝ _ m h := by
    letI : MeasurableSpace Ω := m
    exact hmeas.stronglyMeasurable
  exact ⟨h, hstrong, hae.symm⟩

/-- The sigma-field generated by one canonical coordinate. -/
@[instance_reducible]
def coordinateMeasurableSpace (k : ℕ) : MeasurableSpace (ℕ → E) :=
  MeasurableSpace.comap (fun x : ℕ → E ↦ x k) (inferInstance : MeasurableSpace E)

/-- The sigma-field generated by the first `n` canonical coordinates. -/
@[instance_reducible]
def prefixCoordinateMeasurableSpace (n : ℕ) : MeasurableSpace (ℕ → E) :=
  ⨆ k : Fin n, coordinateMeasurableSpace (E := E) k

theorem prefixCoordinateMeasurableSpace_mono :
    Monotone (prefixCoordinateMeasurableSpace (E := E)) := by
  intro n m hnm
  refine iSup_le fun k ↦ ?_
  exact le_iSup_of_le (Fin.castLE hnm k) le_rfl

theorem prefixCoordinateMeasurableSpace_le (n : ℕ) :
    prefixCoordinateMeasurableSpace (E := E) n ≤
      (inferInstance : MeasurableSpace (ℕ → E)) := by
  change (⨆ k : Fin n, coordinateMeasurableSpace (E := E) k) ≤
    ⨆ k : ℕ, coordinateMeasurableSpace (E := E) k
  apply iSup_mono'
    (f := fun k : Fin n ↦ coordinateMeasurableSpace (E := E) k)
    (g := fun k : ℕ ↦ coordinateMeasurableSpace (E := E) k)
  intro k
  exact ⟨k.val, le_rfl⟩

/-- The increasing finite-coordinate filtration, indexed so stage `n` contains coordinates
`0, ..., n`. -/
def canonicalCoordinateFiltration : Filtration ℕ (inferInstance : MeasurableSpace (ℕ → E)) where
  seq n := prefixCoordinateMeasurableSpace (E := E) (n + 1)
  mono' _ _ hnm := prefixCoordinateMeasurableSpace_mono (Nat.add_le_add_right hnm 1)
  le' n := prefixCoordinateMeasurableSpace_le (n + 1)

theorem iSup_canonicalCoordinateFiltration :
    (⨆ n, canonicalCoordinateFiltration (E := E) n) =
      (inferInstance : MeasurableSpace (ℕ → E)) := by
  apply le_antisymm
  · exact iSup_le fun n : ℕ ↦ (canonicalCoordinateFiltration (E := E)).le n
  · change (⨆ k : ℕ, coordinateMeasurableSpace (E := E) k) ≤ _
    apply iSup_mono'
      (f := fun k : ℕ ↦ coordinateMeasurableSpace (E := E) k)
      (g := fun n : ℕ ↦ canonicalCoordinateFiltration (E := E) n)
    intro k
    refine ⟨k, ?_⟩
    exact le_iSup_of_le (⟨k, Nat.lt_succ_self k⟩ : Fin (k + 1)) le_rfl

/-- Embed two disjoint blocks of length `n`: the initial block and a block beginning at
`m + n`. -/
def twoBlockEmbedding (m n : ℕ) : Sum (Fin n) (Fin n) ↪ ℕ where
  toFun
    | Sum.inl i => i
    | Sum.inr j => m + n + j
  inj' := by
    intro a b hab
    cases a with
    | inl i =>
        cases b with
        | inl j => simp only [Sum.inl.injEq]; exact Fin.ext hab
        | inr j =>
            exfalso
            change (i : ℕ) = m + n + (j : ℕ) at hab
            have hi : (i : ℕ) < n := i.isLt
            have hj : n ≤ m + n + (j : ℕ) := by omega
            omega
    | inr i =>
        cases b with
        | inl j =>
            exfalso
            change m + n + (i : ℕ) = (j : ℕ) at hab
            have hi : n ≤ m + n + (i : ℕ) := by omega
            have hj : (j : ℕ) < n := j.isLt
            omega
        | inr j =>
            simp only [Sum.inr.injEq]
            apply Fin.ext
            change m + n + (i : ℕ) = m + n + (j : ℕ) at hab
            omega

/-- The finite permutation swapping the first block of length `n` with a disjoint block lying
beyond cutoff `m`. -/
noncomputable def swapInitialBlock (m n : ℕ) : Equiv.Perm ℕ :=
  (Equiv.Perm.viaEmbedding
    (Equiv.sumComm (Fin n) (Fin n) : Equiv.Perm (Sum (Fin n) (Fin n)))
    (twoBlockEmbedding m n))

@[simp]
theorem swapInitialBlock_apply_initial (m n : ℕ) (i : Fin n) :
    swapInitialBlock m n i = m + n + i := by
  simpa [swapInitialBlock, twoBlockEmbedding] using
    Equiv.Perm.viaEmbedding_apply (Equiv.sumComm (Fin n) (Fin n))
      (twoBlockEmbedding m n) (Sum.inl i)

@[simp]
theorem swapInitialBlock_apply_far (m n : ℕ) (i : Fin n) :
    swapInitialBlock m n (m + n + i) = i := by
  simpa [swapInitialBlock, twoBlockEmbedding] using
    Equiv.Perm.viaEmbedding_apply (Equiv.sumComm (Fin n) (Fin n))
      (twoBlockEmbedding m n) (Sum.inr i)

theorem swapInitialBlock_isPrefixPermutation (m n : ℕ) :
    IsPrefixPermutation (m + n + n) (swapInitialBlock m n) := by
  intro k hk
  rw [swapInitialBlock]
  apply Equiv.Perm.viaEmbedding_apply_of_notMem
  rintro ⟨i, hi⟩
  cases i with
  | inl j =>
      change (j : ℕ) = k at hi
      omega
  | inr j =>
      change m + n + (j : ℕ) = k at hi
      omega

/-- After swapping blocks, every function of the first `n` coordinates becomes measurable from
the tail beginning at `m`. -/
theorem measurable_swapInitialBlock_prefix (m n : ℕ) :
    @Measurable (ℕ → E) (ℕ → E)
      (tailFromMeasurableSpace (E := E) m)
      (prefixCoordinateMeasurableSpace (E := E) n)
      (permuteSequence (swapInitialBlock m n)) := by
  apply Measurable.of_comap_le
  rw [prefixCoordinateMeasurableSpace, MeasurableSpace.comap_iSup]
  refine iSup_le fun k ↦ ?_
  rw [coordinateMeasurableSpace, MeasurableSpace.comap_comp]
  change MeasurableSpace.comap
      (fun x : ℕ → E ↦ x (swapInitialBlock m n k)) inferInstance ≤ _
  rw [swapInitialBlock_apply_initial]
  exact le_iSup_of_le
    (⟨m + n + (k : ℕ), by omega⟩ : {j : ℕ // m ≤ j}) le_rfl

/-- Strongly measurable finite-prefix functions become tail-measurable after the block swap. -/
theorem StronglyMeasurable.comp_swapInitialBlock_tail {m n : ℕ} {f : (ℕ → E) → ℝ}
    (hf : StronglyMeasurable[prefixCoordinateMeasurableSpace (E := E) n] f) :
    StronglyMeasurable[tailFromMeasurableSpace (E := E) m]
      (f ∘ permuteSequence (swapInitialBlock m n)) :=
  hf.comp_measurable (measurable_swapInitialBlock_prefix m n)

theorem tailFromMeasurableSpace_le_ambient (m : ℕ) :
    tailFromMeasurableSpace (E := E) m ≤
      (inferInstance : MeasurableSpace (ℕ → E)) := by
  refine iSup_le fun k ↦ ?_
  exact Measurable.comap_le (measurable_pi_apply (k : ℕ))

/-- The indicator of an event in the exchangeable sigma-field has an a.e.-equal tail-measurable
representative under an exchangeable probability law. -/
theorem MeasurableSet.aestronglyMeasurable_indicator_exchangeable_tail
    {μ : Measure (ℕ → E)} [IsProbabilityMeasure μ]
    (hX : IsExchangeable (fun k (x : ℕ → E) ↦ x k) μ)
    {A : Set (ℕ → E)} (hA : MeasurableSet[exchangeableMeasurableSpace (E := E)] A) :
    AEStronglyMeasurable[tailMeasurableSpace (E := E)]
      (A.indicator fun _ ↦ (1 : ℝ)) μ := by
  let g : (ℕ → E) → ℝ := A.indicator fun _ ↦ (1 : ℝ)
  let ℱ := canonicalCoordinateFiltration (E := E)
  let c : ℕ → (ℕ → E) → ℝ := fun n ↦ μ[g | ℱ n]
  have hAambient : MeasurableSet A := by
    have hA0 := MeasurableSpace.measurableSet_iInf.mp hA 0
    exact hA0.1
  have hgstrong : StronglyMeasurable g := by
    exact stronglyMeasurable_const.indicator hAambient
  have hgint : Integrable g μ := by
    exact (integrable_const (1 : ℝ)).indicator hAambient
  have hce : Tendsto (fun n ↦ eLpNorm (c n - g) 1 μ) atTop (nhds 0) := by
    apply hgint.tendsto_eLpNorm_condExp
    rw [iSup_canonicalCoordinateFiltration]
    exact hgstrong
  have hcstrong : ∀ n, StronglyMeasurable[ℱ n] (c n) := fun _ ↦ stronglyMeasurable_condExp
  have hginvariant : ∀ m n,
      g ∘ permuteSequence (swapInitialBlock m n) = g := by
    intro m n
    have hAN := MeasurableSpace.measurableSet_iInf.mp hA (m + n + n)
    have hpre := hAN.2 (swapInitialBlock m n) (swapInitialBlock_isPrefixPermutation m n)
    funext x
    have hx : permuteSequence (swapInitialBlock m n) x ∈ A ↔ x ∈ A := by
      simpa only [Set.mem_preimage] using Set.ext_iff.mp hpre x
    simp only [Function.comp_apply, g]
    by_cases hmem : x ∈ A
    · rw [Set.indicator_of_mem hmem, Set.indicator_of_mem (hx.mpr hmem)]
    · rw [Set.indicator_of_notMem hmem, Set.indicator_of_notMem (mt hx.mp hmem)]
  have htailEach : ∀ m,
      AEStronglyMeasurable[tailFromMeasurableSpace (E := E) m] g μ := by
    intro m
    let shifted : ℕ → (ℕ → E) → ℝ := fun n ↦
      c n ∘ permuteSequence (swapInitialBlock m (n + 1))
    have hshiftStrong : ∀ n,
        StronglyMeasurable[tailFromMeasurableSpace (E := E) m] (shifted n) := by
      intro n
      exact StronglyMeasurable.comp_swapInitialBlock_tail (hcstrong n)
    have hnorm : ∀ n,
        eLpNorm (shifted n - g) 1 μ = eLpNorm (c n - g) 1 μ := by
      intro n
      let σ := swapInitialBlock m (n + 1)
      have hfun : shifted n - g = (c n - g) ∘ permuteSequence σ := by
        funext x
        simp only [shifted, σ, Pi.sub_apply, Function.comp_apply]
        rw [show g (permuteSequence σ x) = g x by
          simpa only [Function.comp_apply] using congrFun (hginvariant m (n + 1)) x]
      rw [hfun]
      apply eLpNorm_comp_measurePreserving
      · exact ((hcstrong n).mono (ℱ.le n)).aestronglyMeasurable.sub
          hgstrong.aestronglyMeasurable
      · exact hX.measurePreserving_permuteSequence σ
    have hshiftLp : Tendsto (fun n ↦ eLpNorm (shifted n - g) 1 μ) atTop (nhds 0) :=
      hce.congr' (Filter.Eventually.of_forall fun n ↦ (hnorm n).symm)
    have hshiftMeasure : TendstoInMeasure μ shifted atTop g :=
      tendstoInMeasure_of_tendsto_eLpNorm (by simp)
        (fun n ↦
          ((hshiftStrong n).mono
            (tailFromMeasurableSpace_le_ambient m)).aestronglyMeasurable)
        hgstrong.aestronglyMeasurable hshiftLp
    obtain ⟨ns, -, hns⟩ := hshiftMeasure.exists_seq_tendsto_ae
    exact aestronglyMeasurable_sub_of_tendsto_ae_real
      (tailFromMeasurableSpace_le_ambient m)
      (fun n ↦ (hshiftStrong (ns n)).measurable) hns
  rw [tailMeasurableSpace]
  exact aestronglyMeasurable_iInf_antitone_real
    (fun _ _ hmn ↦ by
      refine iSup_le fun k ↦ ?_
      exact le_iSup_of_le
        ⟨k, hmn.trans k.property⟩ le_rfl)
    tailFromMeasurableSpace_le_ambient
    g htailEach

namespace MeasurableSpace

/-- `m₁ ≤ᵐ[μ] m₂` at the sigma-field level: every `m₁`-measurable event has an
`m₂`-measurable representative modulo `μ`. -/
def LEModulo {Ω : Type*} {mΩ : MeasurableSpace Ω}
    (m₁ m₂ : MeasurableSpace Ω) (μ : @Measure Ω mΩ) : Prop :=
  ∀ ⦃A : Set Ω⦄, MeasurableSet[m₁] A →
    ∃ B : Set Ω, MeasurableSet[m₂] B ∧ A =ᵐ[μ] B

/-- Equality of two sigma-fields after passing to their measure completions. -/
def EqModulo {Ω : Type*} {mΩ : MeasurableSpace Ω}
    (m₁ m₂ : MeasurableSpace Ω) (μ : @Measure Ω mΩ) : Prop :=
  LEModulo m₁ m₂ μ ∧ LEModulo m₂ m₁ μ

end MeasurableSpace

/-- Under an exchangeable probability law, the exchangeable and tail sigma-fields agree modulo
null sets (equivalently, their completions inside the ambient space agree). -/
theorem exchangeableMeasurableSpace_eq_tail_modulo
    {μ : Measure (ℕ → E)} [IsProbabilityMeasure μ]
    (hX : IsExchangeable (fun k (x : ℕ → E) ↦ x k) μ) :
    MeasurableSpace.EqModulo (exchangeableMeasurableSpace (E := E))
      (tailMeasurableSpace (E := E)) μ := by
  constructor
  · intro A hA
    let g : (ℕ → E) → ℝ := A.indicator fun _ ↦ (1 : ℝ)
    have hg : AEStronglyMeasurable[tailMeasurableSpace (E := E)] g μ :=
      MeasurableSet.aestronglyMeasurable_indicator_exchangeable_tail hX hA
    let q : (ℕ → E) → ℝ := hg.mk g
    let B : Set (ℕ → E) := {x | q x = 1}
    have hB : MeasurableSet[tailMeasurableSpace (E := E)] B := by
      exact (hg.stronglyMeasurable_mk.measurable (measurableSet_singleton (1 : ℝ)))
    refine ⟨B, hB, ?_⟩
    filter_upwards [hg.ae_eq_mk] with x hx
    apply propext
    change (x ∈ A ↔ x ∈ B)
    change (x ∈ A ↔ q x = 1)
    by_cases hmem : x ∈ A
    · simp only [hmem]
      simpa [q, g, Set.indicator_of_mem hmem] using hx.symm
    · simp only [hmem, false_iff]
      intro hq
      have hz : q x = 0 := by simpa [q, g, Set.indicator_of_notMem hmem] using hx.symm
      linarith
  · intro A hA
    exact ⟨A, tailMeasurableSpace_le_exchangeableMeasurableSpace A hA,
      Filter.Eventually.of_forall fun _ ↦ rfl⟩

theorem tailMeasurableSpace_eq_limsup_coordinate :
    tailMeasurableSpace (E := E) =
      limsup (coordinateMeasurableSpace (E := E)) atTop := by
  rw [tailMeasurableSpace, limsup_eq_iInf_iSup_of_nat]
  congr 1
  funext n
  rw [tailFromMeasurableSpace, iSup_subtype']
  rfl

/-- Hewitt--Savage zero--one law on canonical sequence space.  The hypotheses expose precisely
the iid ingredients used by the theorem: coordinate independence and equality in law. -/
theorem hewittSavage_zero_one
    {μ : Measure (ℕ → E)} [IsProbabilityMeasure μ]
    (hindep : iIndepFun (fun k (x : ℕ → E) ↦ x k) μ)
    (hident : ∀ i j, IdentDistrib (fun x : ℕ → E ↦ x i) (fun x ↦ x j) μ μ)
    {A : Set (ℕ → E)} (hA : MeasurableSet[exchangeableMeasurableSpace (E := E)] A) :
    μ A = 0 ∨ μ A = 1 := by
  have hX : IsExchangeable (fun k (x : ℕ → E) ↦ x k) μ :=
    isExchangeable_of_iIndepFun
      (fun n ↦ (measurable_pi_apply n).aemeasurable) hindep hident
  obtain ⟨B, hB, hAB⟩ :=
    (exchangeableMeasurableSpace_eq_tail_modulo hX).1 hA
  have hB' : MeasurableSet[limsup (coordinateMeasurableSpace (E := E)) atTop] B := by
    rw [← tailMeasurableSpace_eq_limsup_coordinate]
    exact hB
  have hindep' : iIndep (coordinateMeasurableSpace (E := E)) μ := by
    exact hindep
  have hzero := measure_zero_or_one_of_measurableSet_limsup_atTop
    (fun n ↦ (Measurable.comap_le (measurable_pi_apply n))) hindep' hB'
  rw [measure_congr hAB]
  exact hzero

end ProbabilityTheory
