/-
Copyright (c) 2026 StochLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: StochLean contributors
-/
module

public import StochLean.Probability.Exchangeability.Basic
public import Mathlib.GroupTheory.Perm.ViaEmbedding
public import Mathlib.Probability.Process.FiniteDimensionalLaws

/-!
# Exchangeable and tail sigma-fields on canonical sequence space

The finite-prefix invariant sigma-fields form a decreasing sequence. Their intersection is the
exchangeable sigma-field. The tail sigma-field is contained in it without any distributional
assumption; equality modulo a law is a separate probabilistic theorem and is not built into these
definitions.
-/

@[expose] public section

open MeasureTheory

namespace ProbabilityTheory

variable {E : Type*} [MeasurableSpace E]

/-- Reindex a canonical sequence by a permutation. -/
def permuteSequence (σ : Equiv.Perm ℕ) (x : ℕ → E) : ℕ → E := fun k => x (σ k)

/-- Coordinate permutation as a measurable equivalence on canonical sequence space. -/
def permuteSequenceMeasurableEquiv (σ : Equiv.Perm ℕ) : (ℕ → E) ≃ᵐ (ℕ → E) :=
  MeasurableEquiv.piCongrLeft (fun _ : ℕ => E) σ.symm

@[simp]
theorem permuteSequenceMeasurableEquiv_apply (σ : Equiv.Perm ℕ) (x : ℕ → E) :
    permuteSequenceMeasurableEquiv σ x = permuteSequence σ x := by
  ext k
  change (Equiv.piCongrLeft (fun _ : ℕ => E) σ.symm x) k = x (σ k)
  rw [Equiv.piCongrLeft_apply_eq_cast]
  simp

/-- A permutation is supported in the first `n` coordinates. -/
def IsPrefixPermutation (n : ℕ) (σ : Equiv.Perm ℕ) : Prop :=
  ∀ k, n ≤ k → σ k = k

/-- Restrict a permutation supported in the first `n` coordinates to `Fin n`. -/
def restrictPrefixPermutation (n : ℕ) (σ : Equiv.Perm ℕ) (hσ : IsPrefixPermutation n σ) :
    Equiv.Perm (Fin n) where
  toFun j := ⟨σ j, by
    by_contra h
    have hfix : σ (σ j) = σ j := hσ (σ j) (Nat.le_of_not_gt h)
    have heq : σ j = j := σ.injective hfix
    exact (Nat.not_lt_of_ge (Nat.le_of_not_gt h)) (heq.symm ▸ j.isLt)⟩
  invFun j := ⟨σ.symm j, by
    by_contra h
    have hge : n ≤ σ.symm j := Nat.le_of_not_gt h
    have hfix : σ (σ.symm j) = σ.symm j := hσ (σ.symm j) hge
    have heq : j = σ.symm j := by simpa using hfix
    exact (Nat.not_lt_of_ge hge) (heq ▸ j.isLt)⟩
  left_inv j := by
    ext
    simp
  right_inv j := by
    ext
    simp

@[simp]
theorem restrictPrefixPermutation_apply (n : ℕ) (σ : Equiv.Perm ℕ)
    (hσ : IsPrefixPermutation n σ) (j : Fin n) :
    (restrictPrefixPermutation n σ hσ j : ℕ) = σ j := rfl

/-- The sigma-field of measurable events invariant under every permutation of the first `n`
coordinates. -/
@[instance_reducible]
def prefixInvariantMeasurableSpace (n : ℕ) : MeasurableSpace (ℕ → E) where
  MeasurableSet' s := MeasurableSet s ∧
    ∀ σ : Equiv.Perm ℕ, IsPrefixPermutation n σ → permuteSequence σ ⁻¹' s = s
  measurableSet_empty := by
    constructor
    · exact MeasurableSet.empty
    · intro σ hσ
      simp
  measurableSet_compl := by
    intro s hs
    constructor
    · exact hs.1.compl
    · intro σ hσ
      rw [Set.preimage_compl, hs.2 σ hσ]
  measurableSet_iUnion := by
    intro s hs
    constructor
    · exact MeasurableSet.iUnion fun i => (hs i).1
    · intro σ hσ
      rw [Set.preimage_iUnion]
      congr 1
      funext i
      exact (hs i).2 σ hσ

theorem prefixInvariantMeasurableSpace_antitone :
    Antitone (prefixInvariantMeasurableSpace (E := E)) := by
  intro n m hnm s hs
  exact ⟨hs.1, fun σ hσ => hs.2 σ fun k hnk => hσ k (hnm.trans hnk)⟩

/-- The exchangeable sigma-field is the intersection of all finite-prefix invariant fields. -/
@[instance_reducible]
def exchangeableMeasurableSpace : MeasurableSpace (ℕ → E) :=
  ⨅ n, prefixInvariantMeasurableSpace (E := E) n

theorem exchangeableMeasurableSpace_eq_iInf :
    exchangeableMeasurableSpace (E := E) =
      ⨅ n, prefixInvariantMeasurableSpace (E := E) n := rfl

/-- Omitting the vacuous zero-prefix field does not change the exchangeable sigma-field.  This
is the indexing normalization used by the reverse-martingale mean theorem. -/
theorem iInf_prefixInvariantMeasurableSpace_succ :
    (⨅ n, prefixInvariantMeasurableSpace (E := E) (n + 1)) =
      exchangeableMeasurableSpace (E := E) := by
  rw [exchangeableMeasurableSpace_eq_iInf]
  apply le_antisymm
  · refine le_iInf fun n => ?_
    cases n with
    | zero =>
        exact (iInf_le (fun k => prefixInvariantMeasurableSpace (E := E) (k + 1)) 0).trans
          (prefixInvariantMeasurableSpace_antitone (Nat.zero_le 1))
    | succ n =>
        simpa only [Nat.succ_eq_add_one] using
          (iInf_le (fun k => prefixInvariantMeasurableSpace (E := E) (k + 1)) n)
  · refine le_iInf fun n => ?_
    exact iInf_le (prefixInvariantMeasurableSpace (E := E)) (n + 1)

/-- The sigma-field generated by coordinates from time `n` onward. -/
@[instance_reducible]
def tailFromMeasurableSpace (n : ℕ) : MeasurableSpace (ℕ → E) :=
  ⨆ k : {k : ℕ // n ≤ k}, MeasurableSpace.comap (fun x : ℕ → E => x k) inferInstance

/-- The tail sigma-field. -/
@[instance_reducible]
def tailMeasurableSpace : MeasurableSpace (ℕ → E) :=
  ⨅ n, tailFromMeasurableSpace (E := E) n

theorem tailFromMeasurableSpace_le_prefixInvariant (n : ℕ) :
    tailFromMeasurableSpace (E := E) n ≤ prefixInvariantMeasurableSpace (E := E) n := by
  refine iSup_le fun k => ?_
  apply Measurable.comap_le
  intro s hs
  constructor
  · have hm : Measurable (fun x : ℕ → E => x (k : ℕ)) := by fun_prop
    have hamb : @MeasurableSet (ℕ → E) (inferInstance : MeasurableSpace (ℕ → E))
        ((fun x : ℕ → E => x k) ⁻¹' s) := hm hs
    exact hamb
  · intro σ hσ
    ext x
    simp only [Set.mem_preimage, permuteSequence]
    rw [hσ k k.property]

/-- Every tail event is invariant under every finite permutation. -/
theorem tailMeasurableSpace_le_exchangeableMeasurableSpace :
    tailMeasurableSpace (E := E) ≤ exchangeableMeasurableSpace (E := E) := by
  refine le_iInf fun n => ?_
  exact (iInf_le (fun m => tailFromMeasurableSpace (E := E) m) n).trans
    (tailFromMeasurableSpace_le_prefixInvariant n)

/-- On canonical sequence space, finite-dimensional exchangeability implies invariance of the
entire coordinate-product law under every coordinate permutation. -/
theorem IsExchangeable.identDistrib_permuteSequence
    {μ : Measure (ℕ → E)} [IsFiniteMeasure μ]
    (hX : IsExchangeable (fun k (x : ℕ → E) => x k) μ) (τ : Equiv.Perm ℕ) :
    IdentDistrib (permuteSequence τ) id μ μ := by
  have hperm_meas : AEMeasurable (permuteSequence (E := E) τ) μ := by
    apply Measurable.aemeasurable
    rw [measurable_pi_iff]
    exact fun k => measurable_pi_apply (τ k)
  have hid_meas : AEMeasurable (id : (ℕ → E) → (ℕ → E)) μ := measurable_id.aemeasurable
  rw [identDistrib_iff_forall_finset_identDistrib hperm_meas hid_meas]
  intro I
  let i : I ↪ ℕ :=
    ⟨fun k => τ k, τ.injective.comp Subtype.val_injective⟩
  let j : I ↪ ℕ := Function.Embedding.subtype _
  have h := hX.identDistrib_fintype i j
  convert h using 1 <;> ext x k <;> rfl

/-- Exchangeable laws on canonical sequence space are preserved by coordinate permutations. -/
theorem IsExchangeable.measurePreserving_permuteSequence
    {μ : Measure (ℕ → E)} [IsFiniteMeasure μ]
    (hX : IsExchangeable (fun k (x : ℕ → E) => x k) μ) (τ : Equiv.Perm ℕ) :
    MeasurePreserving (permuteSequence τ) μ μ where
  measurable := by
    rw [measurable_pi_iff]
    exact fun k => measurable_pi_apply (τ k)
  map_eq := by simpa using (hX.identDistrib_permuteSequence τ).map_eq

end ProbabilityTheory
