/-
Copyright (c) 2026 StochLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: StochLean contributors
-/
module

public import StochLean.Probability.Markov.Countable.Recurrence
public import Mathlib.Algebra.Group.Subgroup.Basic
public import Mathlib.NumberTheory.FrobeniusNumber

/-!
# Periodicity of countable-state kernels

The period is obtained from the additive subgroup of `ℤ` generated by all return times.  The
least positive element of that subgroup is the gcd of the return-time set; this construction also
handles infinite return-time sets without introducing a finite-set approximation as a definition.
-/

@[expose] public section

open MeasureTheory Set
open scoped ENNReal MeasureTheory ProbabilityTheory

namespace ProbabilityTheory

namespace Kernel

variable {E : Type*} [MeasurableSpace E]

/-- Times at which `y` has strictly positive transition mass from `x`. -/
def transitionTimes (κ : Kernel E E) (x y : E) : Set ℕ :=
  {n | (κ ^ n) x {y} > 0}

/-- Reachability is nonemptiness of the transition-time set. -/
theorem canReach_iff_transitionTimes_nonempty (κ : Kernel E E) (x y : E) :
    κ.CanReach x y ↔ (κ.transitionTimes x y).Nonempty :=
  Iff.rfl

/-- Transition times concatenate in the Chapman--Kolmogorov order. -/
theorem transitionTimes_add [MeasurableSingletonClass E]
    (κ : Kernel E E) {x y z : E} {m n : ℕ}
    (hm : m ∈ κ.transitionTimes x y) (hn : n ∈ κ.transitionTimes y z) :
    m + n ∈ κ.transitionTimes x z := by
  rw [transitionTimes, Set.mem_ofPred_eq, Kernel.pow_add_apply_eq_lintegral κ m n x
    (MeasurableSet.singleton z)]
  apply (lintegral_pos_iff_support (μ := (κ ^ m) x)
    ((κ ^ n).measurable_coe (MeasurableSet.singleton z))).2
  refine hm.trans_le (measure_mono ?_)
  rintro a rfl
  exact hn.ne'

/-- Return times are closed under addition. -/
theorem transitionTimes_self_add [MeasurableSingletonClass E]
    (κ : Kernel E E) (x : E) {m n : ℕ}
    (hm : m ∈ κ.transitionTimes x x) (hn : n ∈ κ.transitionTimes x x) :
    m + n ∈ κ.transitionTimes x x :=
  transitionTimes_add κ hm hn

/-- Return times form an additive submonoid of the natural numbers. -/
def returnTimeAddSubmonoid [MeasurableSingletonClass E]
    (κ : Kernel E E) (x : E) : AddSubmonoid ℕ where
  carrier := κ.transitionTimes x x
  zero_mem' := by
    change (Kernel.id : Kernel E E) x {x} > 0
    rw [Kernel.id_apply]
    simp
  add_mem' := transitionTimes_self_add κ x

/-- The additive subgroup of integer times generated by return times. -/
def returnTimeSubgroup (κ : Kernel E E) (x : E) : AddSubgroup ℤ :=
  AddSubgroup.closure ((fun n : ℕ => (n : ℤ)) '' κ.transitionTimes x x)

/-- Communicating states generate the same additive subgroup of return times. -/
theorem returnTimeSubgroup_eq_of_communicates [MeasurableSingletonClass E]
    (κ : Kernel E E) {x y : E} (hxy : κ.CanReach x y) (hyx : κ.CanReach y x) :
    κ.returnTimeSubgroup x = κ.returnTimeSubgroup y := by
  have subgroup_le {u v : E} (huv : κ.CanReach u v) (hvu : κ.CanReach v u) :
      κ.returnTimeSubgroup u ≤ κ.returnTimeSubgroup v := by
    obtain ⟨a, ha⟩ := huv
    obtain ⟨b, hb⟩ := hvu
    apply (AddSubgroup.closure_le (κ.returnTimeSubgroup v)).2
    rintro z ⟨n, hn, rfl⟩
    have hlongNat : b + n + a ∈ κ.transitionTimes v v :=
      transitionTimes_add κ (transitionTimes_add κ hb hn) ha
    have hshortNat : b + a ∈ κ.transitionTimes v v :=
      transitionTimes_add κ hb ha
    have hlong : ((b + n + a : ℕ) : ℤ) ∈ κ.returnTimeSubgroup v :=
      AddSubgroup.subset_closure ⟨b + n + a, hlongNat, rfl⟩
    have hshort : ((b + a : ℕ) : ℤ) ∈ κ.returnTimeSubgroup v :=
      AddSubgroup.subset_closure ⟨b + a, hshortNat, rfl⟩
    have hsub := (κ.returnTimeSubgroup v).sub_mem hlong hshort
    have heq : ((b + n + a : ℕ) : ℤ) - ((b + a : ℕ) : ℤ) = (n : ℤ) := by
      push_cast
      ring
    rw [heq] at hsub
    exact hsub
  exact le_antisymm (subgroup_le hxy hyx) (subgroup_le hyx hxy)

/-- Gcd of the return times, using Mathlib's arbitrary-set gcd API. -/
noncomputable def period (κ : Kernel E E) (x : E) : ℕ :=
  Nat.setGcd (κ.transitionTimes x x)

/-- Communicating states have the same period. -/
theorem period_eq_of_communicates [MeasurableSingletonClass E]
    (κ : Kernel E E) {x y : E} (hxy : κ.CanReach x y) (hyx : κ.CanReach y x) :
    κ.period x = κ.period y := by
  apply Nat.dvd_antisymm
  · change Nat.setGcd (κ.transitionTimes x x) ∣ Nat.setGcd (κ.transitionTimes y y)
    rw [Nat.dvd_setGcd_iff]
    intro n hn
    obtain ⟨a, ha⟩ := hxy
    obtain ⟨b, hb⟩ := hyx
    have hlong : a + n + b ∈ κ.transitionTimes x x :=
      transitionTimes_add κ (transitionTimes_add κ ha hn) hb
    have hshort : a + b ∈ κ.transitionTimes x x := transitionTimes_add κ ha hb
    have hdlong := Nat.setGcd_dvd_of_mem hlong
    have hdshort := Nat.setGcd_dvd_of_mem hshort
    apply (Nat.dvd_add_iff_right hdshort).2
    simpa only [add_assoc, add_comm, add_left_comm] using hdlong
  · change Nat.setGcd (κ.transitionTimes y y) ∣ Nat.setGcd (κ.transitionTimes x x)
    rw [Nat.dvd_setGcd_iff]
    intro n hn
    obtain ⟨a, ha⟩ := hxy
    obtain ⟨b, hb⟩ := hyx
    have hlong : b + n + a ∈ κ.transitionTimes y y :=
      transitionTimes_add κ (transitionTimes_add κ hb hn) ha
    have hshort : b + a ∈ κ.transitionTimes y y := transitionTimes_add κ hb ha
    have hdlong := Nat.setGcd_dvd_of_mem hlong
    have hdshort := Nat.setGcd_dvd_of_mem hshort
    apply (Nat.dvd_add_iff_right hdshort).2
    simpa only [add_assoc, add_comm, add_left_comm] using hdlong

/-- Every sufficiently large time in the admissible residue class is a genuine positive return
time.  This is the arithmetic eventual-positivity input used by periodic chain arguments. -/
theorem eventually_mem_transitionTimes_self_of_period_dvd [MeasurableSingletonClass E]
    (κ : Kernel E E) (x : E) :
    ∃ N, ∀ n ≥ N, κ.period x ∣ n → n ∈ κ.transitionTimes x x := by
  obtain ⟨N, hN⟩ := Nat.exists_mem_closure_of_ge (s := κ.transitionTimes x x)
  refine ⟨N, fun n hn hd => ?_⟩
  have hc : n ∈ AddSubmonoid.closure (κ.transitionTimes x x) := by
    exact hN n hn (by simpa only [period] using hd)
  have hle : AddSubmonoid.closure (κ.transitionTimes x x) ≤
      κ.returnTimeAddSubmonoid x :=
    (AddSubmonoid.closure_le).2 (fun _ hm => hm)
  exact hle hc

/-- Once one path from `x` to `y` has been fixed, every sufficiently large admissible return
time at `y` can be appended to it.  This is the residue-class version of eventual positivity for
non-diagonal transitions. -/
theorem eventually_add_mem_transitionTimes_of_canReach [MeasurableSingletonClass E]
    (κ : Kernel E E) {x y : E} (hxy : κ.CanReach x y) :
    ∃ a N : ℕ, a ∈ κ.transitionTimes x y ∧
      ∀ m ≥ N, κ.period y ∣ m → a + m ∈ κ.transitionTimes x y := by
  obtain ⟨a, ha⟩ := hxy
  obtain ⟨N, hN⟩ := eventually_mem_transitionTimes_self_of_period_dvd κ y
  exact ⟨a, N, ha, fun m hm hd => transitionTimes_add κ ha (hN m hm hd)⟩

/-- A state is aperiodic when its period is one. -/
def AperiodicAt (κ : Kernel E E) (x : E) : Prop :=
  κ.period x = 1

/-- A kernel is aperiodic when every state has period one. -/
def IsAperiodic (κ : Kernel E E) : Prop :=
  ∀ x, κ.AperiodicAt x

/-- Global aperiodicity specializes to every state. -/
theorem IsAperiodic.aperiodicAt {κ : Kernel E E} (h : κ.IsAperiodic) (x : E) :
    κ.AperiodicAt x :=
  h x

/-- In an aperiodic communicating class, every sufficiently large time is a positive transition
time between any prescribed pair of states. -/
theorem eventually_mem_transitionTimes_of_canReach_aperiodic
    [MeasurableSingletonClass E] (κ : Kernel E E) {x y : E}
    (hxy : κ.CanReach x y) (hy : κ.AperiodicAt y) :
    ∃ N, ∀ n ≥ N, n ∈ κ.transitionTimes x y := by
  obtain ⟨a, N, ha, hN⟩ :=
    eventually_add_mem_transitionTimes_of_canReach κ hxy
  refine ⟨a + N, fun n hn => ?_⟩
  have ha_le : a ≤ n := le_trans (Nat.le_add_right a N) hn
  have hsub : N ≤ n - a := by omega
  have hy' : κ.period y = 1 := hy
  have hdiv : κ.period y ∣ n - a := by rw [hy']; exact one_dvd _
  have hadd := hN (n - a) hsub hdiv
  simpa [Nat.add_sub_of_le ha_le] using hadd

/-- Global aperiodicity and reachability give the eventual-positivity form used by product-chain
arguments. -/
theorem IsAperiodic.eventually_transitionTimes {κ : Kernel E E}
    [MeasurableSingletonClass E] (hκ : κ.IsAperiodic) {x y : E}
    (hxy : κ.CanReach x y) : ∃ N, ∀ n ≥ N, n ∈ κ.transitionTimes x y :=
  eventually_mem_transitionTimes_of_canReach_aperiodic κ hxy (hκ y)

/-- The cyclic class of states reachable from `x` at times congruent to `r` modulo the period at
`x`.  Indexing by naturals keeps the definition meaningful also before nonzero-period hypotheses
are available; congruent indices define the same class. -/
def cyclicClass (κ : Kernel E E) (x : E) (r : ℕ) : Set E :=
  {y | ∃ n, n ∈ κ.transitionTimes x y ∧ n ≡ r [MOD κ.period x]}

/-- Every reachable state belongs to a cyclic class. -/
theorem mem_cyclicClass_of_canReach (κ : Kernel E E) {x y : E}
    (hxy : κ.CanReach x y) : ∃ r, y ∈ κ.cyclicClass x r := by
  obtain ⟨n, hn⟩ := hxy
  exact ⟨n, n, hn, Nat.ModEq.refl n⟩

/-- Two transition times from `x` to a state which can return to `x` have the same residue modulo
the period.  This is the well-definedness step behind the cyclic decomposition. -/
theorem transitionTimes_modEq_of_canReach_back [MeasurableSingletonClass E]
    (κ : Kernel E E) {x y : E} (hyx : κ.CanReach y x) {m n : ℕ}
    (hm : m ∈ κ.transitionTimes x y) (hn : n ∈ κ.transitionTimes x y) :
    m ≡ n [MOD κ.period x] := by
  obtain ⟨b, hb⟩ := hyx
  have hmb : m + b ∈ κ.transitionTimes x x := transitionTimes_add κ hm hb
  have hnb : n + b ∈ κ.transitionTimes x x := transitionTimes_add κ hn hb
  have hdmb : κ.period x ∣ m + b := Nat.setGcd_dvd_of_mem hmb
  have hdnb : κ.period x ∣ n + b := Nat.setGcd_dvd_of_mem hnb
  have hadd : m + b ≡ n + b [MOD κ.period x] :=
    hdmb.modEq_zero_nat.trans hdnb.modEq_zero_nat.symm
  exact Nat.ModEq.add_right_cancel (Nat.ModEq.refl b) hadd

/-- Distinct residue classes are disjoint inside a communicating class. -/
theorem cyclicClass_disjoint_of_not_modEq [MeasurableSingletonClass E]
    (κ : Kernel E E) (x : E) {r s : ℕ}
    (hback : ∀ y, κ.CanReach x y → κ.CanReach y x)
    (hrs : ¬ r ≡ s [MOD κ.period x]) :
    Disjoint (κ.cyclicClass x r) (κ.cyclicClass x s) := by
  rw [Set.disjoint_left]
  intro y hyr hys
  obtain ⟨m, hm, hmr⟩ := hyr
  obtain ⟨n, hn, hns⟩ := hys
  have hxy : κ.CanReach x y := ⟨m, hm⟩
  have hmn := transitionTimes_modEq_of_canReach_back κ (hback y hxy) hm hn
  exact hrs (hmr.symm.trans (hmn.trans hns))

/-- A positive one-step transition advances the cyclic residue by one. -/
theorem mem_cyclicClass_succ_of_transition [MeasurableSingletonClass E]
    (κ : Kernel E E) (x : E) {r : ℕ} {y z : E}
    (hy : y ∈ κ.cyclicClass x r) (hyz : κ y {z} > 0) :
    z ∈ κ.cyclicClass x (r + 1) := by
  obtain ⟨n, hn, hnr⟩ := hy
  have hone : 1 ∈ κ.transitionTimes y z := by
    simpa [transitionTimes] using hyz
  exact ⟨n + 1, transitionTimes_add κ hn hone, hnr.add_right 1⟩

end Kernel

end ProbabilityTheory
